// AI-generated write-ups of popular claims collected from the open internet.
// Original short summaries — not copied from a single publisher.

const F = "FALSE";
const T = "TRUE";
const P = "PARTIALLY_TRUE";
const U = "UNCERTAIN";

function pack(category, rows) {
  return rows.map(([title, verdict, explanation]) => ({
    category,
    title,
    verdict,
    explanation,
  }));
}

function slugify(title) {
  return title
    .toLowerCase()
    .normalize("NFKD")
    .replace(/['’]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 72);
}

const science = pack("science", [
  ["Humans only use 10% of their brain", F, "Imaging and lesion studies show nearly every brain region has a job. The 10% line is a slogan, not a measurement."],
  ["Goldfish have a three-second memory", F, "Goldfish can remember routes and cues for months. The three-second claim is a joke that stuck."],
  ["Lightning never strikes the same place twice", F, "Tall or conductive spots are hit again and again. Towers and isolated trees are repeat targets."],
  ["Seasons happen because Earth is closer to the Sun in summer", F, "Seasons come from Earth's tilt. The Northern Hemisphere summer is not the closest point to the Sun."],
  ["Deoxygenated blood is blue", F, "Blood is always red. Veins look blue because of how skin and light scatter, not because the blood is blue."],
  ["Bats are blind", F, "Bats can see. Many also use echolocation, which is extra sensing, not a replacement for eyes."],
  ["Ostriches bury their heads in the sand", F, "They lower their heads to the ground to check nests or rest. They do not hide underground."],
  ["Chameleons change color only to match the background", P, "Color shifts signal mood, temperature, and social status. Camouflage is only part of the story."],
  ["Bulls are enraged by the color red", F, "Bulls are largely red-green colorblind. Movement of the cape, not the hue, draws the charge."],
  ["Different parts of the tongue detect different tastes", F, "Taste receptors for sweet, salty, sour, bitter, and umami are spread across the tongue."],
  ["People are left-brained or right-brained", F, "Both hemispheres work together on most tasks. The strict creative-vs-logical split is a pop-psych myth."],
  ["Hair and nails keep growing after death", F, "The body dries and the skin shrinks, which makes hair and nails look longer. They are not growing."],
  ["Pure water is a good conductor of electricity", F, "Very pure water conducts poorly. Dissolved salts and minerals are what make tap water dangerous near current."],
  ["The Great Wall of China is visible from the Moon with the naked eye", F, "From the Moon, even continents are hard to pick out by eye. The Wall is far too narrow."],
  ["A penny dropped from a skyscraper can kill someone", F, "Air resistance keeps a penny from reaching a deadly speed. It can sting. It does not punch through a skull."],
  ["Glass in old windows is thicker at the bottom because glass is a liquid", F, "Old panes were made unevenly and often set with the thicker edge down. Glass is an amorphous solid."],
  ["Mount Everest is the point on Earth farthest from the planet's center", F, "Chimborazo in Ecuador wins that measure because Earth bulges at the equator. Everest is highest above sea level."],
  ["Sharks must swim constantly or they die", P, "Some sharks ram-ventilate and need motion. Others pump water over their gills while still."],
  ["Camels store water in their humps", F, "Humps store fat. Water is conserved through kidneys, nasal passages, and red blood cells."],
  ["Touching a baby bird makes the parents abandon it", F, "Most birds have a weak sense of smell. Parents do not reject a chick because a human touched it."],
  ["Lemming swarms leap off cliffs on purpose", F, "The suicide-march story was staged for a mid-century film. Lemmings do not mass-suicide."],
  ["A mother bird will feed a chick that fell if you put it back", T, "Songbird parents usually keep caring. Putting a fallen nestling back is often the right move."],
  ["Humans have five senses", F, "Beyond the classic five, people sense balance, temperature, pain, body position, and more."],
  ["The Sun is yellow", P, "From space the Sun's light is close to white. Atmosphere scatters blue and can make it look yellow."],
  ["There is a dark side of the Moon that never gets sunlight", F, "The far side faces away from Earth, not away from the Sun. It has a day-night cycle too."],
  ["Black holes suck in everything nearby like cosmic vacuum cleaners", F, "At a given distance, a black hole's gravity matches any equal mass. You have to get close to the horizon."],
  ["In space everything is weightless because there is no gravity", F, "Orbiting crews fall around Earth. Gravity is still there; they are in continuous free fall."],
  ["The North Star is the brightest star in the night sky", F, "Sirius is brighter. Polaris is useful because it sits near the north celestial pole."],
  ["Meteors that hit the ground are still burning hot", P, "The surface can be warm, but the interior of a freshly fallen meteorite is often cool."],
  ["Sound cannot travel in space at all, ever", P, "Empty space has no air to carry ordinary sound. Dense plasma or structures can still carry vibrations."],
  ["Water drains opposite ways in the two hemispheres because of Earth's spin", F, "The Coriolis effect is tiny in a sink. Basin shape and jets decide the swirl."],
  ["Quick sand swallows people whole", F, "It is dense fluidized sand. You can get stuck, but you do not vanish like in movies."],
  ["Lava is the only volcanic danger", F, "Ash, gas, lahars, and pyroclastic flows often kill more people than the glowing rock."],
  ["Diamonds form from compressed coal", F, "Most gem diamonds grow deep in the mantle from carbon sources that are not coal beds."],
  ["The sky is blue because it reflects the ocean", F, "Air molecules scatter shorter blue wavelengths more than red. That scattered light is the sky."],
  ["Raindrops are teardrop shaped", F, "Small drops are nearly round. Larger ones flatten on the bottom like a bun, not a cartoon tear."],
  ["Lightning comes from clouds rubbing together like socks", P, "Charge separation in storms is more complex than laundry static, though ice collisions matter."],
  ["You can outrun lava on foot if you try hard", P, "Some flows are slow. Some move faster than a person. Do not treat lava as a footrace."],
  ["All deserts are hot and sandy", F, "Deserts are defined by dryness. Antarctica is a desert, and many deserts are rocky."],
  ["The equator is the hottest place on Earth", F, "Hot records cluster in subtropical deserts. Clouds and humidity keep many equatorial belts milder."],
  ["Earth is closer to the Sun than to other planets at all times", F, "Sometimes Venus or even Mars can be the closest planet, depending on orbits."],
  ["Jupiter is a failed star", F, "Jupiter would need far more mass to start hydrogen fusion. It is a giant planet, not a brown-dwarf almost-sun."],
  ["Mars is red because it is hot", F, "The color is rusted iron minerals in the dust, not glowing heat."],
  ["Saturn is the only planet with rings", F, "Jupiter, Uranus, and Neptune have rings too. Saturn's are the showiest."],
  ["Pluto was reclassified because it is not round", F, "Pluto is round. It was reclassified because it has not cleared its orbital neighborhood."],
  ["Asteroid belts are crowded junkyards you must dodge", F, "The belt is mostly empty space. Spacecraft cross it without weaving like starfighters."],
  ["A comet's tail always streams behind it like a jet trail", F, "Tails point away from the Sun because of radiation and solar wind, including when the comet heads outward."],
  ["The Moon has a permanent dark face", F, "Same mix-up as the far side. Sunlight reaches the whole lunar surface over a month."],
  ["Stars twinkle because they are burning unsteadily", F, "Twinkle is Earth's air bending starlight. Planets twinkle less because they are tiny disks."],
  ["The Big Dipper is a constellation", F, "It is an asterism, a familiar pattern inside Ursa Major."],
  ["Polaris will always be the North Star", F, "Earth's axis precesses. In a few thousand years, other stars will take the polar role."],
  ["You can see the flag on the Moon with a backyard telescope", F, "The flags are far too small. Even big amateur scopes cannot resolve them."],
  ["NASA lost the technology to go to the Moon", F, "The Saturn V production line ended. The physics was not forgotten; the hardware and budget were."],
  ["Vaccuum of space would make a human explode instantly", F, "You would lose consciousness quickly and suffer injury, but bodies do not burst like balloons."],
  ["Nothing can travel faster than light, including the universe's expansion", P, "Nothing moves through space faster than light. Space itself can stretch so distant galaxies recede faster."],
  ["Heat rises, so upper floors are always warmer for that reason alone", P, "Warm air rises, but insulation, sun, and duct design often matter more than a simple rule."],
  ["Microwaves heat food from the inside out", F, "Microwaves enter from the outside and lose energy as they go. Centers can lag."],
  ["Metal in a microwave always makes sparks", F, "Thin edges and crumpled foil arc. A smooth spoon in a bowl often does nothing dramatic."],
  ["Putting a shell to your ear lets you hear the ocean", F, "You hear ambient noise resonating in the cavity, not a stored seashore."],
  ["A duck's quack does not echo", F, "Quacks echo. The old claim was never a careful acoustic result."],
  ["Bullfrogs croak only when it is about to rain", U, "Calling rises with warmth and moisture, but a croak is not a reliable forecast."],
  ["Swallowed gum stays in your stomach for seven years", F, "Gum is not digested well, but it passes through in days like other leftovers."],
  ["You lose most body heat through your head", F, "Any uncovered skin loses heat. The head is not a special radiator if the rest of you is bare too."],
  ["Cracking knuckles causes arthritis", F, "Studies have not shown that habit causes arthritis. It can annoy people. That is different."],
  ["Eating carrots gives you night-vision like a cat", P, "Vitamin A matters for vision. Extra carrots will not grant superhero eyes."],
  ["Dogs see only in black and white", F, "Dogs are not as rich in color as people, but they are not living in a grayscale movie."],
  ["Cats always land on their feet", P, "They right themselves well, but falls can still injure or kill them."],
  ["A dog's mouth is cleaner than a human's", F, "Dog mouths have plenty of bacteria. Cleaner is not a useful medical comparison."],
  ["Elephants are afraid of mice", U, "Some elephants startle at small scurrying things. A special mouse-phobia is not established."],
  ["An earthworm cut in half becomes two worms", P, "Some pieces of some species can regenerate. Many cuts just kill the worm."],
  ["Houseflies live only a day", F, "Adult houseflies often live weeks. The one-day line confuses them with mayflies."],
  ["Bees die after they sting, so they rarely sting", P, "Honey bee workers often die after stinging mammals. Queens and many other bees can sting more than once."],
  ["All spiders are dangerous to people", F, "Very few species seriously harm humans. Most spiders are harmless or only mildly venomous."],
  ["Daddy longlegs are the most venomous spiders", F, "Harvestmen are not spiders and lack venom glands of that story. Cellar spiders are not record-holders either."],
  ["Sharks do not get cancer", F, "Sharks do get cancer. The claim was used to sell cartilage supplements."],
  ["Dolphins are fish", F, "Dolphins are mammals. They breathe air, nurse, and are warm-blooded."],
  ["Whales spout water", F, "The spout is mostly warm, moist air condensing, plus some spray from around the blowhole."],
  ["Piranhas strip a cow to bones in seconds", F, "They can bite, but the frenzy myth is overblown. Many species scavenge more than they hunt people."],
  ["Crocodiles cry while eating out of guilt", F, "They leak tears while feeding because of how their glands and jaws work, not remorse."],
  ["Penguins live at the North Pole", F, "Wild penguins live in the Southern Hemisphere. Polar bears are the Arctic icon."],
  ["Polar bears have white fur", P, "The hairs are transparent and scatter light. The skin underneath is black."],
  ["Koalas are bears", F, "Koalas are marsupials. The name is a leftover nickname."],
  ["A tomato is a vegetable", P, "Botanically it is a fruit. In kitchens and some laws it is treated as a vegetable."],
  ["Peanuts grow on trees", F, "Peanuts are legumes that develop underground. They are not tree nuts."],
  ["Strawberries are berries", F, "A strawberry is an aggregate accessory fruit. True berries include grapes and bananas."],
  ["Bananas grow on trees", F, "The plant is a giant herb. The 'trunk' is layered leaf bases."],
  ["Carrots were originally orange", F, "Older cultivated carrots were often purple or yellow. Orange became common later in Europe."],
  ["Moss always grows on the north side of trees", F, "Moss likes shade and moisture. In many places that is not strictly north."],
  ["You can tell a tree's age only by cutting it down", P, "Rings are the classic count, but cores and some non-destructive methods exist too."],
  ["Poison ivy is contagious", F, "The oil, urushiol, spreads. The rash itself is not an infection you catch from another person's blisters."],
  ["Venus flytraps eat a lot of meat like a tiny lion", F, "They catch insects for nutrients in poor soil. Photosynthesis still feeds them."],
  ["Sunflowers always face the sun, even as adults", P, "Young heads track the sun. Mature flower heads usually settle facing east."],
  ["Oak trees take hundreds of years before they make acorns", F, "Many oaks produce acorns in a couple of decades, not centuries."],
  ["The five-second rule keeps dropped food safe", F, "Bacteria can transfer immediately. Time on the floor is a weak safety rule."],
  ["Microwave ovens cook with radioactivity that stays in the food", F, "They use non-ionizing microwaves. The food is not left radioactive."],
  ["Leaving a phone in rice is the best way to dry it", P, "Rice is a weak desiccant and can add dust. Power-off and proper drying beat a rice bowl."],
  ["You should rub butter on a burn", F, "Butter traps heat and can worsen the injury. Cool running water is the first step."],
  ["If you are cold you will catch a cold", F, "Colds come from viruses. Winter crowding and dry air help them spread, not chill alone."],
  ["Science has proved that we only use a tiny slice of DNA and the rest is junk", F, "Much non-coding DNA still has roles. 'Junk DNA' was always a rough nickname, not a final map."],
  ["Evolution is 'just a theory' in the casual sense of a guess", F, "In science a theory is a tested framework. Evolution is supported by fossils, DNA, and living populations."],
  ["Humans evolved from modern chimpanzees", F, "Humans and chimps share a common ancestor. One did not turn into the other last week."],
  ["The appendix has no function", P, "It is not essential, but it may play immune and microbiome roles. 'Useless leftover' is too neat."],
  ["You can catch a virus from sitting on a cold rock", F, "Viruses need a path into the body. Temperature of a rock is not an infection."],
  ["Antibiotics kill viruses", F, "Antibiotics target bacteria. They do not treat colds or flu."],
  ["All bacteria are harmful", F, "Most bacteria are harmless or helpful. A minority cause disease."],
  ["Pasteurization means milk is full of chemicals", F, "It is a heat process that reduces pathogens. It is not a chemical dump."],
  ["Organic food contains no pesticides", F, "Organic farming can use approved pesticides. 'Organic' is a method, not a zero-residue guarantee."],
  ["Natural chemicals are safe and synthetic ones are dangerous", F, "Dose and structure matter. Plenty of natural toxins exist, and plenty of synthetics are tightly tested."],
  ["The full moon makes people behave strangely", F, "Large studies do not show a reliable full-moon crime or ER spike. The story outruns the data."],
  ["You can tell the temperature by counting cricket chirps exactly", P, "Chirp rate tracks temperature roughly. It is a fun estimate, not a lab thermometer."],
  ["A red sky at night always means fair weather", P, "The rhyme can work in some mid-latitude west-to-east weather patterns. It is not global law."],
  ["No two snowflakes are alike", P, "At ordinary scales they look unique. At a coarse enough view, similar crystals happen."],
  ["Boiling water freezes faster than cold water every time", P, "The Mpemba effect is real in some setups and absent in others. It is not a kitchen guarantee."],
  ["Hot water is a better solvent so it sanitizes better than chemistry", P, "Heat helps, but sanitizing is about time, temperature, and the cleaner used."],
  ["Oil and water never mix for a mysterious reason", F, "They separate because water molecules prefer each other. Emulsifiers can mix them."],
  ["Rust is just dirt on metal", F, "Rust is iron oxide from a chemical reaction with oxygen and moisture."],
  ["Stainless steel cannot rust", P, "It resists rust well. Chlorides and damage can still corrode it."],
  ["Gold does not tarnish because it is fake if it changes", P, "Pure gold is very unreactive. Alloys and plated pieces can discolor."],
  ["A magnet can scramble a computer permanently through a case from across the room", F, "Everyday fridge magnets are weak at a distance. Storage tech also changed away from old floppy fears."],
  ["The Earth's magnetic field is about to flip next Tuesday and will kill satellites instantly", U, "Reversals happen over long spans. The next one is not a dated doomsday event."],
  ["You can balance an egg only on the equinox", F, "You can balance an egg on many days if the shell and surface cooperate."],
  ["Coriolis force decides how a toilet flushes in Australia", F, "Same as sinks: fixture design wins. Hemisphere spin is negligible in a bowl."],
  ["The Amazon produces 20% of the world's oxygen in a way that would suffocate us if it vanished tomorrow", P, "The forest is vital. Net oxygen to the global atmosphere is more balanced than the slogan."],
  ["Cutting down a rainforest has no climate effect because trees are just plants", F, "Forests store carbon, drive rainfall, and host species. Loss has climate and human costs."],
  ["Recycling plastic means every bottle becomes a new bottle forever", P, "Some recycling loops well. Much plastic is downcycled or not recycled at all."],
  ["Electric cars produce zero emissions, including from the power plant", P, "No tailpipe. The grid mix still matters. Lifetime emissions are still typically lower."],
  ["Nuclear power plants can explode like a city-killing nuclear bomb", F, "Reactor fuel is not bomb-grade geometry. Accidents are serious in other ways."],
  ["Solar panels do not work in cloudy countries", P, "Output drops with clouds, but they still generate. Cold sunny days can be excellent."],
  ["Wind turbines kill so many birds that they are worse than buildings and cats", F, "Turbines do kill birds. Buildings, cats, and habitat loss kill far more."],
  ["Hydroelectric dams are impact-free green energy", F, "They make low-carbon power and also flood land, alter rivers, and can emit methane from reservoirs."],
  ["Science is just opinions in lab coats", F, "Science is a method of testing claims against evidence. Opinions that fail tests get dropped."],
]);

const health = pack("health", [
  ["You should drink eight glasses of water a day", P, "People need fluid, but there is no magic eight. Food, climate, and thirst all count."],
  ["You can sweat out toxins in a sauna and replace a kidney", F, "Sweat cools you. The liver and kidneys do the real detox work."],
  ["Vitamin C prevents you from catching a cold every time", P, "It may slightly shorten some colds. It does not make you immune."],
  ["Feed a cold, starve a fever", F, "Sick people still need fluids and enough food. The rhyme is not a treatment plan."],
  ["Cracking your knuckles will give you arthritis", F, "The habit has not been shown to cause arthritis in studies that looked."],
  ["You must wait 30 minutes after eating before you swim or you will drown", F, "A full stomach can feel uncomfortable. It does not reliably cause drowning cramps."],
  ["Reading in dim light permanently ruins your eyes", F, "It can tire your eyes. It does not prove lasting damage the way the warning sounds."],
  ["Sitting too close to the TV will ruin a child's vision", F, "It may mean the child is nearsighted already. The set itself is not a vision-eater."],
  ["Sugar makes children hyperactive", F, "Blinded studies do not support a general sugar-high. Excitement around parties is a better suspect."],
  ["Breakfast is the most important meal in a way that skipping it always wrecks health", P, "Some people do well with breakfast. Overall diet and sleep matter more than a slogan."],
  ["Detox teas cleanse your liver overnight", F, "Your liver already clears waste. Many teas just make you lose water."],
  ["You can freeze fat off with a cold shower", F, "Cold can feel bracing. It does not spot-reduce fat the way ads imply."],
  ["Spot reduction lets you lose belly fat by doing only crunches", F, "You strengthen muscles. Fat loss is more whole-body than one exercise."],
  ["No pain, no gain means you should train through sharp pain", F, "Useful training can feel hard. Sharp or joint pain is a stop sign, not a badge."],
  ["Women should not lift weights because they will get bulky overnight", F, "Most women do not add huge muscle without years of focused work and calories."],
  ["Sweating more means you burned more fat", F, "Sweat is cooling. A cool room workout can still use plenty of energy."],
  ["Lactic acid is what makes you sore two days later", F, "Delayed soreness is more about muscle repair. Lactate is not a leftover poison."],
  ["Stretching right before a sprint always prevents injury", P, "Warm-up helps. Long static stretches before power moves can even blunt performance."],
  ["You need a sports drink after a 20-minute walk", F, "Water is enough for short easy sessions. Sports drinks suit long, salty sweat losses."],
  ["Chocolate causes acne in everyone", P, "Diet can play a role for some people. Chocolate is not a universal acne switch."],
  ["Greasy food immediately greases your face from the inside", F, "Skin oil is made by glands. A slice of pizza is not piped to your pores."],
  ["You should pop every pimple to help it heal", F, "Squeezing can push inflammation deeper and scar. Leave most of them alone."],
  ["Shaving makes hair grow back thicker", F, "The blunt tip feels coarser. The follicle is not reprogrammed."],
  ["Hair can turn white overnight from fright", F, "Hair color is set as it grows. Sudden white is not how pigment works."],
  ["You lose 100 hairs a day so baldness is just that number going up", P, "Shedding is normal. Pattern hair loss is a different process."],
  ["Brushing harder cleans better", F, "Hard scrubbing wears enamel and gums. Soft bristles and time beat force."],
  ["Bleeding gums are normal if you brush", F, "Healthy gums should not bleed as a habit. It often means inflammation."],
  ["You only need to see a dentist if something hurts", F, "Many problems start quietly. Checks catch decay and gum disease early."],
  ["Whitening toothpaste remodels enamel to a new color permanently", P, "Some remove surface stains. They do not rebuild a new tooth."],
  ["Mouthwash can replace brushing", F, "Rinse can help. It does not scrape plaque the way a brush and floss do."],
  ["Sleeping fewer hours is a badge of success", F, "Chronic short sleep hurts mood, immunity, and driving. It is not elite biology."],
  ["You can bank sleep on the weekend and cancel weekday debt completely", P, "Catch-up helps a bit. It does not fully erase a week of restriction."],
  ["Alcohol helps you sleep better", P, "It can make you drowsy, then fragment the second half of the night."],
  ["Screens have no effect on sleep for anyone", F, "Evening light and scrolling can delay sleep for many people."],
  ["Snoring is always harmless", F, "It can be benign. It can also mark sleep apnea that needs care."],
  ["You can catch the flu from being underdressed", F, "Flu is a virus. Cold weather can crowd people indoors, which spreads it."],
  ["The flu shot gives you the flu", F, "Inactivated shots cannot cause influenza. Feeling off for a day is an immune response."],
  ["Vaccines are full of antifreeze that is meant to poison people", F, "Ingredients are in tiny, studied amounts. The poison story skips dose and purpose."],
  ["Natural immunity is always better than vaccine immunity", P, "Infection can immunize and can also hospitalize. Vaccines aim for the first without the second."],
  ["Antibiotics will help a typical cold end faster", F, "Colds are viral. Antibiotics will not shorten them and can cause harm."],
  ["You should finish leftover antibiotics from last year for a new sore throat", F, "Old leftover pills may be wrong, expired, or incomplete. Get current advice."],
  ["All swollen lymph nodes mean cancer", F, "Infection is a common cause. Persistent or unusual nodes need a clinician, not a guess."],
  ["A fever should always be brought to normal right away", P, "Fever is part of the response. Very high fevers and vulnerable people need care."],
  ["Starving a fever is good medicine", F, "Hydration and enough calories matter. Starvation is not a therapy."],
  ["Chicken soup is useless folklore", P, "It hydrates and comforts. It is not a cure, and it is not nothing."],
  ["You spread colds only when you feel sick", F, "People can shed virus before symptoms. Handwashing still matters."],
  ["Hand sanitizer makes soap obsolete", P, "Alcohol gels help when hands are not filthy. Visible dirt still wants soap and water."],
  ["Washing hands for two seconds is enough if the water is hot", F, "Time and soap matter more than scalding water."],
  ["You cannot get sunburned on a cloudy day", F, "UV comes through clouds. Shade and season still matter."],
  ["A base tan protects you like clothing", F, "A tan is injury. It gives only slight extra protection, not a free pass."],
  ["Sunscreen is needed only at the beach", F, "UV hits sidewalks, snow, and windows. Daily face use is common advice for a reason."],
  ["Higher SPF means you can stay out all day without reapplying", F, "SPF is not a time machine. Sweat and time wear it off."],
  ["You cannot burn in the water", F, "Water reflects UV. Swimmers burn."],
  ["Tanning beds are a safe way to get vitamin D", F, "They raise skin-cancer risk. Vitamin D has safer sources."],
  ["Vitamin D is only in sunlight, never in food", F, "Fatty fish, some eggs, and fortified foods also provide it."],
  ["More vitamins are always better", F, "Fat-soluble vitamins can build up. Mega-doses are not automatically healthy."],
  ["If a little antioxidant is good, a huge dose is better", F, "High-dose supplements have failed big hopes in some trials. Food patterns beat megapills."],
  ["Superfoods cancel an otherwise poor diet", F, "One berry bowl does not outvote a week of ultra-processed meals."],
  ["Carbs are inherently fattening", F, "Extra calories from any source can add fat. Whole-food carbs can fit a healthy pattern."],
  ["Fat in food automatically becomes body fat that same afternoon", F, "Energy balance and overall intake matter more than one nutrient's name."],
  ["Eating fat gives you heart disease by itself", P, "Replacing saturated fat with better fats can help. Fear of all fat is outdated."],
  ["Cholesterol in food is the same as cholesterol in your arteries, one to one", F, "Blood cholesterol is more about liver production and overall diet than one egg."],
  ["Eggs are dangerous for everyone", F, "For most people, eggs can fit a healthy diet. Individual risk still varies."],
  ["Brown sugar is a health food compared with white sugar", F, "It is still sugar with a hint of molasses. The metabolic hit is similar."],
  ["Honey is not sugar because it is natural", F, "Honey is sugar plus traces of other compounds. Dose still counts."],
  ["Diet soda is proven to be harmless for every outcome", U, "It can help some people cut sugar. Long-term effects are still studied."],
  ["You must drink juice to get fruit benefits", F, "Whole fruit has fiber the juice often lacks. Juice is easy to overdrink."],
  ["Celery has negative calories that make you lose weight while chewing", F, "Celery is low-calorie. Chewing it does not burn more than it contains in a magical way."],
  ["Late-night eating automatically stores fat", P, "Total intake and food quality matter more. Some people do overeat at night."],
  ["A cheat day erases a week of careful eating", F, "One day changes little. A pattern of huge swings can still stall goals."],
  ["You can target liver fat with a detox juice", F, "Liver fat falls with weight loss and better habits, not a two-day cleanse."],
  ["Colon cleanses remove pounds of old waste", F, "The colon is not a trash attic. Aggressive cleanses can harm."],
  ["Probiotics fix every gut problem", P, "Some strains help some conditions. A random bottle is not a cure-all."],
  ["Gluten is toxic to everyone", F, "Celiac disease and some sensitivities are real. Most people digest gluten without illness."],
  ["Dairy causes mucus that always worsens a cold", P, "Some people notice thicker saliva. Dairy does not create extra respiratory mucus for everyone."],
  ["Milk makes bones unbreakable if you drink a gallon", F, "Calcium and vitamin D matter. More milk is not infinite armor."],
  ["Kids will outgrow a peanut allergy if you hide peanuts forever, always", P, "Guidance changed toward early introduction for many infants. Follow a clinician, not a forum."],
  ["Food expired yesterday is always deadly", F, "Dates are often about quality. Some foods last; some do not. Use sense and type of food."],
  ["Leftovers are safe as long as they smell fine", P, "Smell misses some pathogens. Time and temperature still matter."],
  ["Rare hamburger is as safe as rare steak", F, "Ground meat mixes surface bacteria through the patty. Steak searing is different."],
  ["You can tell if meat is cooked by the color alone", F, "Color can mislead. A thermometer is more reliable."],
  ["Alcohol kills all food bacteria in a marinade", F, "It is not a sterilizer at kitchen strengths. Keep raw meat handled as raw."],
  ["Pregnant people should eat for two in calories", F, "Needs rise, but not by a second full adult diet."],
  ["You cannot exercise while pregnant", F, "Many pregnancies allow adjusted activity. The old total-rest rule is outdated for most."],
  ["Morning sickness only happens in the morning", F, "Nausea can arrive any time of day."],
  ["You can predict a baby's sex with a wedding ring on a string", F, "It is a guessing game. Ultrasound and tests are how clinicians check."],
  ["Breastfeeding is instinctive and never needs help", F, "It is natural and it is a learned skill. Lactation help is common and useful."],
  ["Formula is poison", F, "Breastfeeding has benefits. Safe formula feeds millions of babies."],
  ["Teething causes high fever and diarrhea", P, "Mild fuss is common. High fever needs another explanation."],
  ["You should add cereal to a bottle to make a baby sleep through", F, "It is not a safe sleep hack and does not teach nights."],
  ["Kids need to be extra clean or their immune systems stay weak", P, "Some dirt exposure is normal. Serious hygiene still prevents disease."],
  ["Chickenpox parties are a good idea", F, "The disease can be severe. Vaccination is the safer path where available."],
  ["You can treat appendicitis at home with herbs", F, "Appendicitis is an emergency. Delay can rupture."],
  ["If you can walk, your ankle is not broken", F, "People walk on fractures. Pain and swelling still need a check."],
  ["Put heat on a fresh sprain immediately", F, "Early on, rest and cold are the usual first steps. Heat is for later stiffness."],
  ["Tilt your head back for a nosebleed", F, "That sends blood down the throat. Lean forward and pinch the soft nose."],
  ["Butter belongs on a burn", F, "It can make burns worse. Use cool water and clean covering."],
  ["Urine is sterile and heals jellyfish stings", F, "Urine is not a sterile medicine cabinet. Use vinegar or salt water as local guidance says."],
  ["You should suck venom from a snakebite", F, "Cutting and sucking can worsen tissue injury. Immobilize and get emergency care."],
  ["A tourniquet belongs on every bleeding cut", F, "Direct pressure is first. Tourniquets are for severe limb bleeding, not a paper cut."],
  ["Hydrogen peroxide is the best way to clean every wound every day", P, "It can irritate healing tissue. Gentle water and soap are often better."],
  ["You should keep a wound dry and sealed from air forever", P, "Moist wound care often heals better. Filthy wetness is not the same as a clean dressing."],
  ["Cracking your neck is a safe way to treat a headache every morning", P, "Some people feel relief. Aggressive twisting has rare but serious risks."],
  ["Back pain always means you need a scan today", F, "Many episodes improve with time and simple care. Red flags change that."],
  ["Bed rest for weeks is the best cure for ordinary back pain", F, "Gentle movement usually beats long bed rest."],
  ["Mental health problems are just a lack of willpower", F, "Depression and anxiety are health conditions. Effort helps treatment; it is not the whole disease."],
  ["Kids cannot have depression", F, "Children and teens can. Mood change that lasts deserves attention."],
  ["Talking about suicide makes people do it", F, "Asking directly is a standard safety step. Silence does not protect."],
  ["Addiction is only a moral failing", F, "Biology, environment, and choice all show up. Treatment works better than shame."],
  ["You cannot get addicted to prescription medicine if a doctor wrote it", F, "Some prescriptions can still lead to dependence. Follow the plan and ask questions."],
  ["Vaping is just water vapor", F, "Aerosol can carry nicotine and other chemicals. It is not a mist of tap water."],
  ["Smoking a little is safe because athletes used to do it", F, "There is no safe tobacco smoke dose for the lungs and vessels."],
  ["Secondhand smoke is harmless", F, "It raises disease risk for people nearby, including children."],
  ["Coffee stunts children's growth", F, "Evidence does not show coffee shrinks kids. Sleep and total diet matter more."],
  ["Decaf coffee has no caffeine", P, "Decaf is lower, not always zero."],
  ["You can sober up quickly with a cold shower and coffee", F, "Only time lowers blood alcohol. Coffee makes a wide-awake drunk."],
  ["One drink a day is proven to be healthy for everyone", U, "Older headlines oversold this. Many guidelines now lean toward less is better."],
  ["You cannot get liver trouble unless you drink every day", F, "Binge patterns and other diseases also harm the liver."],
  ["Pain means damage is happening right now, always", F, "Pain is a signal that can outlast injury or appear without a new tear."],
  ["If a treatment works, you will feel it immediately", F, "Many helpful treatments take days or weeks. Instant sensation is not the test."],
  ["Placebos mean the person was faking", F, "Placebo responses are real brain-body effects. Faking is a different thing."],
  ["Alternative medicine that is 'natural' cannot interact with drugs", F, "St. John's wort and others change drug levels. Natural is not non-interactive."],
  ["You can replace insulin with cinnamon if you have type 1 diabetes", F, "Type 1 needs insulin. Spices are not a substitute."],
  ["Diabetes is caused only by eating sugar", F, "Type 2 risk includes weight, genes, and activity. Type 1 is autoimmune."],
  ["People with diabetes cannot eat any fruit", F, "Portions and pairing matter. Fruit is not banned by default."],
  ["High blood pressure always causes a headache", F, "It is often silent. That is why checks matter."],
  ["You can feel when your cholesterol is high", F, "There are usually no symptoms. A blood test answers it."],
  ["Atrial fibrillation is always obvious", F, "It can be silent and still raise stroke risk."],
  ["Heart disease is a man's disease", F, "It is a leading killer of women too. Symptoms can look different."],
  ["Stroke symptoms that fade in minutes can be ignored", F, "A TIA is a warning. It needs urgent care."],
  ["You should drive yourself to the hospital if you think you are having a heart attack", F, "Call emergency services. Driving can delay care and is unsafe."],
  ["CPR is useless if you are not a professional", F, "Hands-only CPR from bystanders saves lives. Dispatchers can coach you."],
  ["The recovery position is for every unconscious person including trauma", P, "It helps many breathing casualties. Spinal or other trauma changes the plan."],
  ["You should put something in the mouth of a person having a seizure", F, "That breaks teeth and your fingers. Protect the head and wait it out, then recovery position when it ends."],
  ["All chest pain is heartburn", F, "Heart and stomach can mimic each other. New severe pain needs a check."],
  ["Antacids fix a heart attack", F, "If you are unsure, treat it as an emergency, not as last night's pizza."],
]);

const history = pack("history", [
  ["Napoleon was extremely short", F, "He was around average height for his time. British cartoons and inch conversions built the legend."],
  ["Vikings wore horned helmets into battle", F, "The horns are a later costume idea. Real war helmets were practical iron caps."],
  ["The Great Wall is a single ancient wall built in one dynasty", F, "It is many walls and rebuilds across centuries, not one continuous ancient ribbon."],
  ["Columbus discovered that Earth is round", F, "Educated Europeans already knew it was a sphere. The fight was over the size of the ocean."],
  ["Columbus landed in what is now the United States", F, "His first landfall was in the Caribbean. He never saw the land that became the US mainland in the usual school-story way."],
  ["The Emancipation Proclamation freed every enslaved person in the United States the day it was signed", P, "It applied to states in rebellion, not automatically to Union slave states. The 13th Amendment finished the legal end."],
  ["The first Thanksgiving looked like a modern grocery-ad feast", F, "The 1621 meal was a harvest gathering with different foods and a more complicated politics."],
  ["Witches were burned in Salem", F, "The Salem accused were hanged, and one was pressed. Burning was not the New England method."],
  ["Medieval people thought the Earth was flat", F, "Scholars used a spherical Earth. The flat-Earth Middle Ages is a later cartoon."],
  ["People in the Middle Ages did not bathe", P, "Bathing habits varied. The idea of a thousand unwashed years is too neat."],
  ["Chastity belts were common medieval devices", F, "Most surviving stories and objects are later jokes or fakes, not everyday medieval kit."],
  ["The Iron Maiden was a standard medieval torture tool", F, "The famous spiked cabinets are largely later inventions for display."],
  ["Nero fiddled while Rome burned", F, "Fiddles did not exist. The story is hostile gossip about a ruler who was elsewhere in the tale."],
  ["Caesar's last words were 'Et tu, Brute?' in English-play form as a sure quote", U, "Shakespeare made the line famous. Ancient reports differ."],
  ["Cleopatra was Egyptian by ancestry in the simple schoolbook sense", P, "She ruled Egypt and learned Egyptian. Her dynasty was Macedonian Greek."],
  ["The pyramids were built by disposable slave masses with no skill", P, "Workers included seasonal laborers and specialists who were housed and fed. The slave-only picture is too crude."],
  ["Aliens built the Egyptian pyramids", F, "We have tools, worker villages, ramps research, and an Egyptian building tradition. No aliens required."],
  ["The library of Alexandria's loss erased almost all ancient knowledge in one night", P, "There were several hits over time. Knowledge also lived in copies elsewhere."],
  ["Greek statues were always plain white marble", F, "Many were painted. The white museum look is what time and later taste left us."],
  ["Spartans were emotionless super-soldiers with no culture", F, "They had music, poetry, and politics. The movie version is a diet Sparta."],
  ["All Romans spoke classical textbook Latin in the street", F, "Everyday speech was different from literary Latin, and the empire was multilingual."],
  ["Gladiators always fought to the death", F, "Fights were costly. Many bouts ended with surrender and a decision, not a corpse."],
  ["Christians were constantly thrown to lions as everyday sport for centuries", P, "Persecutions happened. The nonstop coliseum reel is exaggerated."],
  ["The Trojan Horse is an established archaeological fact", U, "The war stories mix poetry and possible memory. A literal giant horse is unproven."],
  ["King Arthur definitely ruled a shining medieval England as in the films", U, "Arthur is legend layered on possible war-leader memories. Camelot cinema is fiction."],
  ["Robin Hood was a single well-documented gentleman thief", U, "The stories gathered many outlaw tales. A tidy biography is not sitting in one archive."],
  ["The Black Death was caused by bad smells alone", F, "It was a disease, now tied mainly to Yersinia pestis. Miasma was the old theory."],
  ["People in 1348 understood germs the way we do", F, "Germ theory is 19th century. They used the ideas they had."],
  ["The Renaissance started because people suddenly became smart", F, "It was a shift in money, cities, texts, and patronage, not a new brain model."],
  ["Shakespeare did not write his plays because he lacked a university degree", U, "Oxfordian theories exist. The working playwright from Stratford remains the mainstream view."],
  ["Shakespeare invented hundreds of everyday words from nothing", P, "He popularized and first-recorded many. Not every credit is a true coinage."],
  ["The Spanish Inquisition killed tens of millions", F, "It was brutal and real. The cartoon death tolls are inflated."],
  ["Pirates buried treasure on every island and drew an X", F, "A few hid loot. The map-and-X ritual is storybook."],
  ["Pirates said 'arrr' as a historical dialect fact", F, "The growl is mostly from later stage and film voices."],
  ["Blackbeard was a giant cartoon with lit fuses in his beard every Tuesday", P, "He used terrifying display. The Saturday-morning version is extra paint."],
  ["The United States Constitution freed the slaves", F, "It allowed slavery to continue. Later amendments changed that."],
  ["George Washington had wooden teeth", F, "His dentures used metal, ivory, and human teeth. Not a carpenter's leftover."],
  ["Washington chopped down a cherry tree and confessed", F, "Parson Weems invented the moral tale after Washington died."],
  ["Betsy Ross sewed the first Stars and Stripes as a settled fact", U, "The family story appeared later. It is possible and unproven."],
  ["Paul Revere finished a solo midnight ride yelling the British are coming", P, "He was one rider, was detained, and would not have used that wording in a colony of British subjects."],
  ["The Civil War was only about states' rights in a way that leaves slavery out", F, "Declarations and politics put slavery at the center. States' rights was often the right to hold people."],
  ["Abraham Lincoln started the Civil War to abolish slavery on day one", P, "He wanted to save the Union first; emancipation became central as the war went on."],
  ["The Gettysburg Address was a flop that nobody liked", P, "Some papers shrugged. It did not stay a flop."],
  ["Cowboys were almost all white men from Virginia", F, "A large share of working cowboys were Black, Mexican, and Native."],
  ["The Wild West was nonstop daily gunfights in every town", F, "Some places were violent. The Hollywood hourly duel is fiction."],
  ["Settlers found an empty unused continent", F, "Millions of Native people lived here with nations, farms, and cities."],
  ["The first people in the Americas walked over last Tuesday in one simple path", P, "Peopling was earlier and more complex than one cartoon land-bridge moment."],
  ["The 1920s were only flappers and jazz for everyone", F, "Most people were not living a movie. Farmers and factory workers had different 1920s."],
  ["The New Deal ended the Great Depression by itself on a known afternoon", P, "It reshaped the state and relief. World War II spending also changed the economy."],
  ["World War I was caused by one sandwich in Sarajevo and nothing else", F, "The assassination lit a fuse on alliances, militarism, and empire. It was not only lunch."],
  ["The Treaty of Versailles is the only reason World War II happened", P, "It mattered. Depression, politics, and choices in the 1930s mattered too."],
  ["Hitler was democratically unstoppable from the first election", P, "Nazis rose through votes, deals, intimidation, and then dismantled democracy."],
  ["The Holocaust is exaggerated or did not happen", F, "It is one of the best-documented crimes in history. Denial is false."],
  ["Japan surrendered only because of the Soviet invasion, so the bombs did nothing", U, "Historians still argue weights. Both the bombs and the Soviet entry sit in the record."],
  ["The US entered World War II the day Poland was invaded", F, "Germany invaded Poland in 1939. The US declared war after Pearl Harbor in 1941."],
  ["D-Day was the day Germany surrendered", F, "D-Day was June 1944 in Normandy. Germany surrendered in May 1945."],
  ["The French only surrendered and never resisted", F, "France fell fast in 1940. Resistance and Free French forces still fought."],
  ["Switzerland hid in the Alps and had no wartime dealings", P, "It stayed formally neutral and also had banking and border realities that were not innocent cartoons."],
  ["The Cold War never turned hot anywhere", F, "Korea, Vietnam, Afghanistan, and proxy wars were hot for the people in them."],
  ["The Berlin Wall was built by the West to keep people in", F, "East Germany built it to stop emigration to the West."],
  ["The Cuban Missile Crisis lasted years of daily duck-and-cover", F, "The acute crisis was thirteen days in 1962, on top of a longer Cold War."],
  ["Lee Harvey Oswald's guilt is unknown to all historians equally", U, "Official findings named Oswald. Conspiracy debates continue in public."],
  ["The moon landing was faked in a studio", F, "Independent tracking, rocks, and later imaging of the sites bury the hoax claim."],
  ["Watergate was a third-rate burglary with no bigger story", F, "It was a cover-up that reached the presidency and ended it."],
  ["The Soviet Union collapsed because Reagan said a single sentence", P, "External pressure played a part. Internal economic and political failure did the heavy work."],
  ["The 1990s internet was invented by Al Gore in the sense that he wrote TCP/IP", F, "Gore backed funding and talked policy. He did not invent the protocols."],
  ["The Y2K bug did nothing, so the work was wasted", F, "A lot of remediation happened. The quiet night was partly because people fixed it."],
  ["The 2008 crash was a surprise that nobody in finance could have seen", P, "Many warnings existed. Incentives still ran the other way."],
  ["Ancient Greeks had no word for blue so they could not see blue", F, "Language and color terms vary. Eyes still saw the sea."],
  ["Medieval maps put Jerusalem in the center so they failed at geography", P, "Some maps were theological diagrams. Sailors also used practical charts."],
  ["The Church banned zero and Arabic numerals everywhere for centuries", P, "Adoption was uneven and sometimes resisted. Europe still took up the system."],
  ["Galileo was executed for saying Earth moves", F, "He was tried and spent his later life under restriction. He was not executed."],
  ["Darwin recanted evolution on his deathbed", F, "The recant story is a later invention. He did not take it back."],
  ["Einstein failed math in school", F, "He was strong in math. A later myth mixed up exams and ages."],
  ["Newton got the whole of gravity from one apple hitting his head", P, "He did think about falling apples. The cartoon bonk is extra."],
  ["Archimedes ran naked shouting Eureka through town as a sure biography", U, "It is a later colorful story. The buoyancy idea is real."],
  ["Van Gogh sold only one painting", P, "He sold little in life. The 'only one' line is too tidy."],
  ["Mozart was poisoned by Salieri", U, "Rivalry stories are dramatic. Proof of murder is not there."],
  ["Beethoven was fully deaf overnight as a young man", P, "Hearing loss was progressive. He still composed."],
  ["The Titanic was advertised as unsinkable in those exact words by the builders as a guarantee", P, "The reputation of being practically unsinkable was around. The smug slogan grew after the sinking."],
  ["The band on the Titanic never played", F, "Survivors reported they played as the ship went down."],
  ["Third-class passengers were locked below the whole time as a simple complete story", P, "Barriers and chaos existed. The movie version is not a full archival map."],
  ["The Hindenburg exploded because it was filled with hydrogen and nothing else mattered", P, "Hydrogen was the lift gas. The ignition story still has debate about coatings and sparks."],
  ["The Chernobyl accident made the whole planet uninhabitable", F, "It was a catastrophe for people nearby and for workers. The whole Earth did not empty."],
  ["The Spanish flu started in Spain", F, "Spain reported freely in wartime. The name stuck; origin is still researched."],
  ["World War I ended at the eleventh hour and fighting stopped everywhere at once", P, "The armistice time is famous. Some units kept firing until the clock, and news lagged."],
  ["The US Constitution originally included women as voters", F, "Voting rules were left to states and excluded most women until the 19th Amendment."],
  ["The 19th Amendment let all women vote immediately in practice", P, "White women gained a national right. Many Black, Native, and other women still faced barriers."],
  ["Stonewall was the first time gay people ever resisted", F, "It was a turning-point uprising, not the first resistance."],
  ["The Civil Rights Act ended racism", F, "It banned key forms of legal discrimination. Social and economic inequality continued."],
  ["Nelson Mandela was president of South Africa in the 1960s", F, "He was imprisoned. He became president in 1994."],
  ["The Berlin Wall fell because one DJ played a song", F, "A press-conference mix-up and mass pressure opened the gates. Soundtrack myths came later."],
  ["Ancient Rome had no apartments or traffic", F, "Insulae were crowded housing. The city had noise, carts, and rules about them."],
  ["Samurai always followed an ancient unchanging bushido from the year 800", F, "The popular code was written and rewritten later. Practice varied."],
  ["Ninjas dressed in black pajamas as everyday wear", F, "The stage outfit is theater. Real spies dressed to blend in."],
  ["The samurai sword can cut a gun barrel in half as a normal feat", F, "Good steel cuts well. Movie physics is still movie physics."],
  ["Genghis Khan only destroyed and never administered", F, "The conquests were brutal and the empire also ran post, law, and trade routes."],
  ["The Mongols were only a small raiding club", F, "They built the largest contiguous land empire in history."],
  ["China was always isolated from the rest of the world", F, "Silk Road and sea trade ran for centuries. Isolation is a later stereotype."],
  ["India was a single kingdom for all of antiquity", F, "It was many states and cultures. Empires came and went."],
  ["Africa had no cities before Europeans arrived", F, "Great Zimbabwe, Timbuktu, Benin, and others were urban centers."],
  ["The Americas had no agriculture before 1492", F, "Maize, potatoes, beans, and more were domesticated here."],
  ["Aboriginal Australians arrived a few centuries ago", F, "Their history on the continent is tens of thousands of years deep."],
  ["The Olympic Games of ancient Greece included women athletes in all events", F, "The main festival was male. Separate games existed for women."],
  ["The marathon commemorates a runner who died in Athens after a 26.2 mile exact course", P, "The legend of Pheidippides is old. The modern distance was standardized much later."],
  ["The first modern Olympics were a perfect copy of ancient ones", F, "Coubertin's games were a 19th-century invention with ancient flavor."],
  ["The United Nations was founded after World War I", F, "The League of Nations followed WWI. The UN was founded in 1945."],
  ["The League of Nations stopped World War II", F, "It failed to stop the 1930s aggressions. The war came anyway."],
]);

const technology = pack("technology", [
  ["Incognito mode makes you anonymous on the internet", F, "It skips some local history. Your ISP, workplace, and the site can still see the visit."],
  ["Deleting a file instantly vaporizes it off the drive", F, "The directory entry goes away first. Data often remains until overwritten."],
  ["A paperclip in the factory reset hole always wipes iCloud too", F, "A local reset is not the same as signing out of every cloud copy."],
  ["Macs do not get malware", F, "They are a smaller target, not an immune species. Mac malware exists."],
  ["Linux is impossible for ordinary people to use", P, "Some setups are geeky. Mainstream desktops are ordinary computers."],
  ["Opening the case of a PC voids every law of physics", F, "You can open a tower. Warranties vary. Static care still matters."],
  ["More megapixels always means a better camera", F, "Sensor size, lenses, and processing often matter more than a megapixel race."],
  ["A higher milliamp-hour number always means a phone lasts two days", P, "Capacity helps. Screen, radios, and software decide the day."],
  ["Fast charging destroys every battery on week one", P, "Heat and chemistry matter. Modern phones manage charge; abuse still ages cells."],
  ["You should drain a lithium phone to zero every night", F, "Old nickel advice. Lithium prefers mid-range charges, not deep funerals."],
  ["Leaving a phone at 100% on the charger all night always explodes it", F, "Phones taper charge. Heat and cheap gear are the real villains, not the last percent alone."],
  ["Airplane mode is only for takeoff theater", P, "Radios can interfere with older avionics rules. It also saves battery."],
  ["A signal booster app can create bars from nowhere", F, "Software cannot invent radio that is not there. Most 'boosters' are junk."],
  ["Closing all apps on your phone every hour saves lots of battery", F, "Modern systems manage RAM. Constant killing can use more power to relaunch."],
  ["Dark mode always saves huge battery on every screen", P, "It helps on OLED when pixels are actually off. On many LCDs the win is tiny."],
  ["A VPN makes you untraceable and unlocks every crime legally", F, "A VPN shifts trust to the VPN. It is not a invisibility cloak or a law."],
  ["Public Wi-Fi is safe if the coffee shop is nice", F, "Open networks can be watched or spoofed. HTTPS helps; nice couches do not."],
  ["HTTPS in the address bar means the site is trustworthy", P, "It means the pipe is encrypted. A scam site can still buy a certificate."],
  ["A long password that is a single dictionary word plus 1 is strong", F, "Length helps when it is unpredictable. Password1 is famous and weak."],
  ["Changing your password every week to Password2 is good hygiene", F, "Forced frequent changes produced Password3. Unique and long is better."],
  ["Security questions like your first pet are unguessable", F, "That data leaks or is public. They are weak recovery keys."],
  ["Two-factor authentication is only for spies", F, "It blocks a lot of ordinary account theft. It is for anyone with email."],
  ["SMS codes are the strongest 2FA", P, "They beat nothing. App or hardware keys beat SMS, which can be swapped."],
  ["If a site has a padlock, phishing is impossible", F, "Look-alike domains get padlocks too. Check the name, not only the icon."],
  ["Antivirus means you can click any attachment", F, "Antivirus helps. Curiosity still opens ransomware."],
  ["Ransomware is a myth used to sell software", F, "Hospitals and cities have paid and recovered for a reason. It is real."],
  ["Updates exist only to ruin your workflow", F, "They also patch holes. Skipping them is how old bugs stay open."],
  ["The cloud is a fluffy warehouse in the sky", F, "It is someone else's computers in buildings. The icon is a metaphor."],
  ["Files in the cloud cannot be lost", F, "Providers fail, accounts lock, and sync deletes. You still need a backup plan."],
  ["Once you post online you can always delete it everywhere", F, "Copies, screenshots, and archives remain. Delete is not a time machine."],
  ["Social networks show you everything your friends post in order", F, "Feeds are ranked. You see what the algorithm picks."],
  ["If it is on the internet it must be true", F, "The internet copies errors at light speed. Check sources."],
  ["Wikipedia can never be used because anyone can edit it", P, "Anyone can edit many pages; many pages are watched. It is a start, not a last word."],
  ["Google's first result is always the best answer", F, "It is a popular result. Popular is not the same as correct."],
  ["Incognito plus a VPN plus a new email means the ads stop knowing you", P, "You look like a new user until behavior and logins rejoin the graph."],
  ["Clearing cookies deletes your entire government file", F, "Cookies are browser crumbs. Agencies do not live in your chocolate-chip folder."],
  ["Your phone is listening to every word to serve one ad for shoes", P, "Apps collect a lot. The always-listening-for-ads story is overclaimed; targeting is already good without it."],
  ["Bluetooth drains the battery even when nothing is connected, always by 80%", P, "Radios use power. Modern idle Bluetooth is usually small."],
  ["5G causes COVID-19", F, "A virus caused the pandemic. Radio bands do not invent a coronavirus."],
  ["5G is a mind-control ray", F, "It is a faster phone network. The conspiracy skips physics and medicine."],
  ["Wi-Fi routers cause cancer at home like a tiny reactor", U, "Wi-Fi is non-ionizing and low power. Big cancer claims are not established."],
  ["You should stand far from a microwave or it will cook your organs", P, "Ovens are shielded. Standing across the kitchen is optional, not a movie plot."],
  ["Smart meters are secretly broadcasting your conversations", F, "They report usage data. They are not a house bug by design."],
  ["Electric cars will all brick when it rains", F, "High-voltage systems are sealed and tested. Rain is the normal environment."],
  ["Electric cars are worse for the climate than gasoline in every country", F, "Manufacturing has a carbon cost. Over the life, they usually win where grids are mixed or clean."],
  ["Self-driving cars are fully solved and never need a driver", F, "Driver-assist is not full autonomy. Edge cases still need humans."],
  ["Cruise control is the same as autopilot on a highway forever", F, "Cruise holds speed. It does not watch the road for you."],
  ["ABS makes it safe to slam brakes on ice without steering care", P, "ABS helps you steer while braking. Ice still has little grip."],
  ["Four-wheel drive means you can stop shorter on snow", F, "It helps you go. Stopping is still tires and brakes."],
  ["Premium gas gives every economy car extra horsepower", F, "If the manual says regular, premium is usually wasted money."],
  ["Idling warms the engine better than driving gently", F, "A light drive warms it faster. Long idling wastes fuel."],
  ["You should change oil every 1,000 miles no matter what the maker says", F, "Modern intervals are longer. Follow the book, not 1960s folklore."],
  ["Bigger tires always make a car faster", F, "They can change gearing, weight, and grip. Faster is not automatic."],
  ["Diesel engines cannot be clean in any sense", P, "Old diesels were filthy. Newer systems cut a lot of soot and NOx, with their own scandals."],
  ["Hybrid cars do not use gasoline on the highway", P, "Many hybrids use the engine at speed. The electric bit shines in stop-and-go."],
  ["A bigger phone battery pack that gets very hot is a good bargain", F, "Heat and cheap cells start fires. Cheap mystery packs are a hazard."],
  ["Any USB cable is the same as any other", F, "Data, charge rate, and shielding differ. Some cables are charge-only."],
  ["Lightning vs USB-C is only about the shape, never the chips", F, "Connectors hide different protocols. The shape is not the whole story."],
  ["Wireless charging is magic with no energy loss", F, "It is convenient and less efficient. The extra energy becomes heat."],
  ["A screen protector makes a phone unbreakable", F, "It can save the glass from scratches and some hits. The frame can still die."],
  ["Waterproof ratings mean you can take a phone scuba diving forever", F, "IP codes are lab tests. Seals age, and depth ratings are limited."],
  ["Restarting a computer is a superstition", F, "It clears stuck processes and updates. It is boring and often works."],
  ["The Recycle Bin is a secure wipe", F, "It is a holding folder. Emptying it is still not forensic erasure."],
  ["Incinerating a hard drive is the only way anyone deletes files", F, "Overwrites and secure-erase tools exist. Fire is for the dramatic ending."],
  ["SSDs cannot fail because they have no moving parts", F, "Flash wears and controllers die. Backups still matter."],
  ["RAID is a backup", F, "RAID can survive a disk failure. It does not survive theft, fire, or a bad sync."],
  ["The more RAM you have, the faster every old laptop becomes", P, "If you were swapping, RAM helps. A weak CPU stays weak."],
  ["You need a discrete GPU to send email", F, "Integrated graphics send email just fine."],
  ["Mining Bitcoin with a laptop is a good side hustle in 2026", F, "The network difficulty makes laptop mining a heater that loses money."],
  ["Cryptocurrency is completely anonymous", F, "Many chains are public ledgers. Exchanges also know your name."],
  ["NFTs always include the copyright of the image", F, "You often buy a token that points at a file. The license is a separate question."],
  ["The blockchain cannot be used for anything dumb", F, "It can timestamp and settle. It can also store a lot of expensive trivia."],
  ["AI chatbots understand like a person and never bluff", F, "They predict text. They can sound sure and still invent sources."],
  ["If an AI says it with confidence, it checked a database", F, "Confidence is a style. Verification is your job."],
  ["AI art has no energy or data cost", F, "Training and serving models use energy and scraped data. The cost is just not on your power bill."],
  ["Captchas prove you are a good person", F, "They try to tell people from bots. They do not score morals."],
  ["Robots will take every job next month", U, "Some tasks automate. Whole-economy timelines are guesses sold as headlines."],
  ["The first computer was a 1990s beige box", F, "Computing is older: wartime machines, mainframes, and before that, human computers."],
  ["The internet and the web are the same word for the same thing", F, "The internet is the network. The web is one service on it, like email."],
  ["Email is instant and never delayed", F, "It is usually fast. Servers queue, filter, and sometimes sit."],
  ["Reply-all is a victimless click", F, "It can leak a list or spam a company. Think before you spray."],
  ["Bcc is a good place to hide a secret from the server", F, "Recipients in Bcc are hidden from each other. The mail still exists on servers."],
  ["A PDF cannot have malware", F, "Bad PDFs exist. Do not treat the format as a holy shield."],
  ["QR codes are always safe because they are just pictures", F, "They encode a link. The link can be a trap."],
  ["Smart TVs do not have microphones or tracking", F, "Many do. Read the settings if you care."],
  ["Turning a device off at the wall is the same as sleep", F, "Off is off. Sleep still sips power and can wake for updates."],
  ["Smart bulbs cannot be on a botnet", F, "Cheap IoT devices get drafted. Passwords and updates matter even for lamps."],
  ["Your printer is a simple appliance with no security story", F, "Network printers have been left open and full of old documents."],
  ["Factory reset removes every hidden account token", P, "It helps a lot. Some paired clouds need a separate sign-out."],
  ["Open source means no one is responsible and it is always insecure", F, "Anyone can read the code. That can mean more review, not less care."],
  ["Closed source means hackers cannot find bugs", F, "Attackers do not need the source. Hidden is not hardened."],
  ["The dark web is only criminals", P, "It includes hidden services for privacy and for crime. The phrase is not a single alley."],
  ["Tor makes you a superhero in every jurisdiction", F, "It helps anonymity and it is slow and misused. It is not a cape."],
  ["End-to-end encryption means the company can read the plaintext anytime", F, "Proper E2E means they cannot. Marketing words still get stretched."],
  ["A screenshot is a legally binding signature", F, "It can be evidence. It is not automatically a contract."],
  ["Deepfakes are always easy to spot by looking at the hands", P, "Hands were a tell. The tells move as the tools improve."],
  ["You can trust a viral video because it has a lot of views", F, "Views measure spread. They do not measure truth."],
  ["Old phones become slow only because companies hate you", P, "Batteries age and new apps get heavier. Some throttling has also been real and fined."],
  ["A factory-new battery will stay at 100% health for five years of fast charging in a hot car", F, "Heat and high charge wear lithium. Chemistry is not a loyalty program."],
  ["You need to defrag an SSD weekly", F, "Defrag is for spinning disks. TRIM and wear leveling are the SSD story."],
  ["More RGB lights make a PC faster", F, "Lights are decoration. Benchmarks do not run on neon."],
  ["Overclocking is free performance with no extra heat", F, "You pay in power, heat, and sometimes lifespan."],
  ["A screen's refresh rate does not matter if you cannot see 24 fps film", F, "Film cadence and interactive smoothness are different. High refresh is noticeable in motion."],
  ["8K is required to enjoy a 50-inch living-room TV from the couch", F, "Viewing distance often makes 4K already past the eye's limit."],
  ["HDR means the picture is just more saturated", P, "HDR is about brightness range. Some modes also punch color."],
  ["Streaming always uses less data than a download of the same film", P, "A long stream can exceed a single download, especially at high bitrate."],
  ["Buffering means your internet is broken forever", F, "It can be the app, the CDN, or Wi-Fi next to a microwave. Try a test, then panic."],
  ["The best Wi-Fi is always the highest channel number", F, "Congestion and walls matter. Auto or 5 GHz nearby often beats a superstition."],
  ["Hiding your Wi-Fi name makes it invisible to attackers", F, "Hidden SSIDs still leak. Use a strong password and modern encryption."],
  ["WEP is fine if your password is long", F, "WEP is broken. Use WPA2 or WPA3."],
  ["Guest Wi-Fi is pointless at home", F, "It keeps visitors off your printers and shared disks. It is a small good idea."],
  ["IoT devices should all live on the main LAN with the laptops", P, "Convenience yes. A separate network reduces how far a hacked bulb can walk."],
  ["A strong magnet will wipe a modern phone from your pocket", F, "Phones use flash, not a spinning magnetic platter. Magnets can bother compasses and some accessories."],
  ["X-ray airport machines erase your laptop drive", F, "Normal luggage X-rays are not a wipe tool. Keep backups for ordinary reasons."],
  ["You must eject a USB stick or the files are always destroyed", P, "Write caching can lose the last save. Eject is still smart."],
  ["Formatting a drive once with a quick format meets legal destruction standards", F, "Quick format removes the table. The bits can remain."],
]);

const culture = pack("culture", [
  ["Fortune cookies come from ancient China", F, "They were popularized in California by Japanese and Chinese bakeries. China did not invent the table-side prophecy."],
  ["French fries were invented in France", F, "The stronger origin story is Belgian. The name is about the cut, not Paris."],
  ["The customer is always right as a law of nature", F, "It was a shop slogan. Some customers are wrong and some are abusive."],
  ["You must spend 10,000 hours or you cannot be good at anything", P, "Practice matters. The exact number is a pop-science rounding, not a law."],
  ["Money cannot buy any kind of happiness", P, "Money eases misery up to a point. It does not purchase meaning on a card swipe."],
  ["Opposites attract as a dating rule that always wins", P, "Some differences work. Shared values usually last longer than a movie trope."],
  ["People use only a tiny part of their potential, like the brain myth for life goals", U, "Motivation talk is not a measurement. People can grow; they are not 10% alive."],
  ["A black cat crossing your path causes bad luck", F, "It is a superstition. The cat is busy being a cat."],
  ["Breaking a mirror means seven years of bad luck", F, "It means you need a new mirror and a dustpan."],
  ["Walking under a ladder is cursed", F, "It can be unsafe if someone is working. The curse is optional."],
  ["Friday the 13th is statistically doomed", F, "It is an unlucky-number story. The calendar is not out to get you."],
  ["Knocking on wood changes fate", F, "It is a habit from older tree and church lore. The table does not file paperwork."],
  ["A wish on a falling star is a binding cosmic contract", F, "Meteors burn. Wishes stay wishes."],
  ["The tooth fairy is a documented historical person", F, "It is a modern-ish childhood story. Put the tooth where your family puts it."],
  ["Santa's current red suit was invented only by Coca-Cola", P, "Coke ads popularized a look. Red Santas existed earlier."],
  ["Christmas has always been a single global date and custom", F, "Dates and customs vary. Many pieces are local and later."],
  ["Pumpkins are the original jack-o'-lanterns of Ireland", P, "Turnips and other roots came first. Pumpkins were an American upgrade."],
  ["Halloween is an American invention with no older roots", F, "It draws on All Hallows and older harvest and saint days. The candy industry is newer."],
  ["The Easter Bunny is in the earliest Christian texts", F, "Eggs and hares are folk additions. The Gospels do not mention a rabbit logistics network."],
  ["Groundhog Day forecasts are scientifically tight", F, "It is a festival. Meteorology is a better forecast."],
  ["Wedding rings go on the left hand because a vein runs to the heart", F, "The vein story is lore. Customs differ by culture and century."],
  ["Brides wear white because it has always meant purity in every culture", F, "White weddings were popularized in the 19th century. Other colors have long histories."],
  ["The best man exists to fight off the bride's family", U, "There are old kidnapping-of-the-bride stories. Modern groomsmen are ceremonial."],
  ["Rice thrown at weddings kills birds as a rule", F, "Uncooked rice is not a bird poison in the way the rumor said. Some venues still ban it for mess."],
  ["You must give a gift that matches a registry or you have failed etiquette forever", F, "Registries help. A thoughtful gift or presence still counts."],
  ["It is illegal to have a dirty car in some countries as an urban-legend statute", U, "A few places have had visibility or junk-car rules. The viral 'illegal to be dusty' posts are often fake."],
  ["You will be fined for chewing gum in every part of Singapore in the cartoon way", P, "Singapore restricts gum imports and littering. It is not a chewing death penalty."],
  ["In Britain, everyone has afternoon tea with the Queen as a daily habit", F, "Tea is common. Palace tea is not a national 4 p.m. requirement."],
  ["All Mexican food is extremely spicy", F, "Mexican cuisines are diverse. Heat is a choice, not a passport stamp."],
  ["Sushi means raw fish", F, "Sushi is about seasoned rice. Fish can be raw, cooked, or absent."],
  ["MSG is a dangerous chemical invented to make you ill", F, "It is a flavor salt used in many kitchens. Symptom stories are mostly not backed in blinded tests."],
  ["Wasabi on most restaurant plates is the real rhizome", P, "Many shops serve horseradish dyed green. Real wasabi is rarer and pricier."],
  ["Fortune and cookie quality predict your week", F, "The paper is printed in a factory. Enjoy the cookie."],
  ["A coin in a fountain guarantees the wish", F, "It funds the fountain's city or a cleanup. The water is not a bank for fate."],
  ["Beginner's luck is a statistical law", P, "New players can run hot. Variance is not a charm."],
  ["Hot hands in basketball are proven every time a player hits two in a row", P, "Streaks happen. Whether they exceed chance is a long argument."],
  ["The Super Bowl is won by the team with the better animal mascot", F, "Mascots are branding. Blocking and throwing decide it."],
  ["A curse on a stadium is the reason a team loses", F, "Teams lose because of play, injuries, and luck. Ghosts do not cover the spread."],
  ["Olympic amateurism still means athletes cannot earn money", F, "The old amateur rule faded. Modern Olympians can be professionals."],
  ["The marathon distance was chosen by the ancient Greeks as 26.2", F, "The modern 26.2 miles was set in the 20th century around a royal box, not Marathon village math."],
  ["A coin flip is perfectly fair every time", P, "A good flip is close. Slight bias exists in the physics if you look hard."],
  ["You can learn a language in a week with a miracle app", F, "Apps help practice. Fluency takes time and use."],
  ["Children soak up languages with zero effort and no need to hear them", F, "Kids are good learners. They still need lots of input."],
  ["English is the official language of the United States by the Constitution", F, "The Constitution does not set one. English is dominant in practice."],
  ["The word 'literally' has only one permitted meaning forever", P, "Usage includes emphasis. Dictionaries record how people speak."],
  ["Text slang is destroying the ability to write", P, "People codeswitch. Formal writing is a skill you still practice in school and work."],
  ["Shakespearean English is Old English", F, "Old English is Beowulf. Shakespeare is early modern."],
  ["The letter Z is called 'zed' only to be difficult", F, "Zed is the older British name. Zee is the American one."],
  ["You cannot start a sentence with 'and'", F, "Teachers used it to stop rambling. Writers start sentences with 'and' on purpose."],
  ["Ending a sentence with a preposition is always an error", F, "That rule was copied from Latin. Natural English ends with them all the time."],
  ["Split infinitives are illegal", F, "'To boldly go' is English. The ban is a classroom ghost."],
  ["The Oxford comma is grammatically illegal in America", F, "It is a style choice. Some guides want it; some do not."],
  ["All slang is new and from the internet", F, "Slang is old. The internet just publishes it faster."],
  ["Emoji are not communication", F, "They carry tone. They are not a full language for contracts."],
  ["Cursive is required to read any historical document", P, "It helps with many hands. Plenty of print sources exist too."],
  ["The best books are always the hardest to read", F, "Difficulty is not virtue. Clarity can be art."],
  ["Audiobooks do not count as reading", P, "You get the story and language. You miss some spelling and reread control."],
  ["A first edition paperback is always the most valuable copy", F, "Collectors care about true firsts, condition, and demand. Format is not a rule."],
  ["All modern art is a joke that anyone could drip", U, "Some work is conceptual and easy to mock. Skill and context still sit behind a lot of it."],
  ["Photography is not art because a machine clicks", F, "Choosing light, frame, and time is still making. The machine is a tool."],
  ["Auto-tune means the singer has no talent", P, "It can paper over pitch. It is also used as an effect on purpose."],
  ["Vinyl sounds better because analog is always truer", P, "Some people prefer the color. A good digital copy can be more accurate."],
  ["Loud music is better music", F, "Loudness is a mastering fad. Dynamics can be the point."],
  ["Classical music makes you a genius if you play it to a baby once", F, "The Mozart effect was oversold. Lessons and time are how skill grows."],
  ["Any movie that made money is good, and any flop is bad art", F, "Box office is a market. Taste and craft are different scoreboards."],
  ["Sequel movies are always worse", P, "Many are. Some are the point of the story. A number in the title is not a review."],
  ["Book was better is a law, not a preference", F, "Adaptation changes medium. Preferring the book is fine; it is not physics."],
  ["You can judge a country by one tourist restaurant", F, "A menu near a station is a sample of one kitchen. Cuisine is bigger than that."],
  ["Tipping 20% is the law in every country", F, "It is a US custom in many restaurants. Other places include service or treat tipping as optional."],
  ["It is rude to eat with your hands in every culture", F, "Many cuisines are eaten by hand, with rules. Utensils are not a moral universal."],
  ["Slurping noodles is always rude", F, "In some places it is normal or even a compliment. Context is the etiquette."],
  ["You must finish every plate or you insult the cook, worldwide", P, "Some hosts read a clean plate as praise. Others read it as still hungry. Ask the room."],
  ["Talking about money is illegal in polite society everywhere", F, "Taboos vary. Some cultures talk price openly."],
  ["Eye contact is respectful in every culture", F, "In some places steady eye contact is a challenge. Respect has local rules."],
  ["Smiling at strangers is universally friendly", P, "It can welcome or confuse. Not every street is a smile contest."],
  ["Being late is a personality that cannot be helped", P, "Culture and transit play a part. Repeated lateness is still a choice you can change."],
  ["Small talk is fake and therefore worthless", F, "It is a social lubricant. You do not have to love it for it to work."],
  ["Introverts cannot lead or speak in public", F, "Energy source is not competence. Many speakers recover alone later."],
  ["Extroverts are always happier", F, "Personality is not a happiness score. Sleep and friends matter more."],
  ["Only children are doomed to be selfish", F, "Sibling count is a weak destiny. Parenting and peers show up too."],
  ["Birth order determines your whole personality", P, "Family roles can shape habits. They do not stamp a fixed soul."],
  ["Men are from Mars and cannot do laundry", F, "Skills are taught. Planets are not chore charts."],
  ["Women are naturally bad at maps", F, "Spatial skill is trained. The stereotype is not a GPS."],
  ["Left-handed people are more creative as a proven rule", U, "The idea is popular. Evidence is mixed and small."],
  ["Handedness can be trained away without cost", P, "Some people switch. Forcing a child can be stressful and unnecessary."],
  ["Crossing your arms means you hate the speaker", F, "People get cold and comfortable. Body-language posters overclaim."],
  ["Liars always look up and to the left", F, "Eye-direction charts are pop psychology. Look at consistency, not a compass."],
  ["You can spot a liar by one tell every time", F, "People fidget for many reasons. There is no single Pinocchio muscle."],
  ["First impressions cannot be updated", F, "They stick more than they should. They are still not destiny."],
  ["Multitasking lets you do two thinking jobs at full quality", F, "You switch. Each switch costs. Some pairings, like walking and chatting, are easier."],
  ["Willpower is a muscle that only dies if you eat a cookie", P, "Ego-depletion headlines were oversold. Sleep and habits still help."],
  ["Positive thinking alone cures serious disease", F, "Attitude can help coping. It is not a substitute for treatment."],
  ["If you can dream it you can do it, including violating physics", F, "Goals need means. Gravity does not take vision boards."],
  ["Luck is never a factor if you work hard", F, "Work changes odds. Birthplace and timing still exist."],
  ["The customer review with one star is always a bot", U, "Some are fake. Some are a bad night. Read the pattern."],
  ["Viral means important", F, "Viral means contagious. Cat videos prove the difference."],
  ["Cancel culture was invented in 2018 and never existed before", F, "Public shaming is old. The platform is new."],
  ["Nobody ever changed their mind because of an argument online", P, "Lurkers change more than the thread. Still, many fights are sport."],
  ["A quote posted on a sunset proves the famous person said it", F, "Misattribution is a sport. Check the source."],
  ["Old sayings are true because they are old", F, "Some survived because they help. Some survived because they rhyme."],
  ["Blood is thicker than water means family always comes first in the original saying", P, "The short proverb is used that way. Longer variants exist and get argued."],
  ["The exception proves the rule means exceptions confirm rules", P, "In older English, prove can mean test. People now use it both ways."],
  ["Curiosity killed the cat, so stop asking questions", F, "The rest of the saying is about satisfaction bringing it back. Ask anyway."],
]);

import { extraMyths } from "./myth-catalog-extra.mjs";

export function buildCatalog() {
  const all = [...science, ...health, ...history, ...technology, ...culture, ...extraMyths];
  const seen = new Set();
  const out = [];

  for (const item of all) {
    const slug = slugify(item.title);
    if (!slug || seen.has(slug)) continue;
    seen.add(slug);
    out.push({ ...item, slug });
  }

  return out;
}

export { slugify };