// Widely repeated popular claims. Short original write-ups, not copied from one source.

const F = "FALSE";
const T = "TRUE";
const P = "PARTIALLY_TRUE";
const U = "UNCERTAIN";

function pack(category, rows) {
  return rows.map(([title, verdict, explanation]) => ({
    category,
    title,
    verdict,
    explanation,
  }));
}

export const popularMyths = [
  ...pack("culture", [
    ["You swallow eight spiders a year in your sleep", F, "The statistic was invented as a warning about bad internet facts. Spiders have no reason to crawl into a breathing mouth."],
    ["Never wake a sleepwalker or they will die", F, "Waking someone can confuse them. It does not kill them. Steering them away from stairs is the useful part."],
    ["Breaking a mirror brings seven years of bad luck", F, "The seven-year clock is folklore. A broken mirror is a mess and a cut risk, not a curse timer."],
    ["Walking under a ladder is always unlucky", F, "It can be unwise if someone is working above you. The unlucky part is gravity, not a hex."],
    ["Opening an umbrella indoors summons disaster", F, "Wet floors and poked eyes are the real indoor-umbrella problem."],
    ["A black cat crossing your path ruins the day", F, "The cat is commuting. Your calendar does not update."],
    ["Knocking on wood cancels a jinx", F, "It is a habit from older tree-spirit stories. It does not edit probability."],
    ["Throwing salt over your left shoulder blinds the devil", F, "It is a table superstition. It mostly startles whoever is sitting there."],
    ["Friday the 13th is statistically the most dangerous day", F, "Some people change plans that day. The date itself is not a hazard."],
    ["Finding a four-leaf clover forces good fortune", F, "They are uncommon. Luck is not stored in the leaflet count."],
    ["A rabbit's foot is a lucky charm that works", F, "It is a grim souvenir. It does not change dice."],
    ["Make a wish on a shooting star and it arrives", F, "Meteors are dust burning up. Wishes still need a plan."],
    ["Birthday candles grant a wish if you blow them in one breath", F, "It is a party game. Germs on the cake are the more measurable result."],
    ["Step on a crack and break your mother's back", F, "A sidewalk rhyme. Pavement joints are not a medical device."],
    ["Itchy palms mean money is coming in or going out", F, "Skin itches. Banks do not take that signal."],
    ["A ringing in the ear means someone is talking about you", F, "Tinnitus and noise are common. Gossip is optional."],
    ["Sneezing means someone is remembering you", F, "Dust, colds, and pepper explain more than telepathy."],
    ["Ouija boards are moved by spirits", F, "People move the planchette without noticing. That ideomotor effect is well shown."],
    ["Orbs in photos are ghosts", F, "They are usually dust, insects, or flash reflection."],
    ["Cold spots in a house prove a haunting", P, "Drafts, insulation gaps, and open vents do that job every day. Ghosts are the extra story."],
    ["3 a.m. is the devil's hour by physics", F, "It is a folklore clock. Nothing in the atmosphere flips at 3:00."],
    ["The Bermuda Triangle swallows ships by a known mysterious force", F, "Busy sea lanes, weather, and normal wreck rates explain the stories. No special force has been measured."],
    ["Area 51 is confirmed to store alien craft", U, "It is a real secret test site. Alien hardware is the rumor, not a public inventory."],
    ["Crop circles are always made by visitors from space", F, "People with boards have made famous ones. Weather and fungus make messy rings, not perfect logos."],
    ["Bigfoot is a documented ape species", U, "Footprints and blurry film exist. A living population has not been shown."],
    ["The Loch Ness Monster is a surviving plesiosaur", F, "The loch is young in geologic terms. Famous photos were hoaxed or misread wakes and wood."],
    ["Alligators breed in New York sewers", F, "A few dumped pets made headlines. There is no underground gator city."],
    ["Walt Disney is frozen under the theme park", F, "He was cremated. The freezer story is a tour-guide myth."],
    ["Pop Rocks and soda will explode your stomach", F, "The candy fizz is tiny. A kid actor's death was from something else; the rumor stuck to the packet."],
    ["A tooth left in a glass of cola overnight dissolves", F, "Cola is acidic enough to roughen enamel over time. It does not vanish a tooth by morning like a cartoon."],
    ["Fortune cookies are a traditional Chinese dessert", F, "The cookies took off in Japanese and later American Chinese restaurants. They are not an ancient Beijing custom."],
    ["Chop suey is a classic dish from China", F, "It is a Chinese-American plate. The origin stories are messy; the menu is local."],
    ["General Tso's chicken is a Hunan home recipe", F, "It was popularized in American restaurants. The general did not need a sweet-fried lunch."],
    ["Tikka masala is an ancient temple dish from India", P, "Spice and tandoor cooking are old. The creamy restaurant version is a later hit, with competing origin stories."],
    ["French fries were invented in France", P, "Belgium and France both claim fried potatoes. The American name is not a birth certificate."],
    ["The sandwich was invented only so a gambler would not leave the table", P, "The Earl of Sandwich story is famous. People put food in bread earlier."],
    ["Tequila bottles always contain a worm", F, "Some mezcal bottles have a larva as marketing. Tequila usually does not."],
    ["Absinthe makes you hallucinate from wormwood magic", F, "Old bottles were strong alcohol. Thujone at drinkable levels is not LSD."],
    ["Sushi always means raw fish", F, "Sushi is about seasoned rice. Fish can be raw, cooked, or skipped."],
    ["Wasabi in most restaurants is the real Japanese plant", P, "The real rhizome is pricey. Many tubes are horseradish dyed green."],
    ["MSG in restaurant food is a poison invented to make you sick", F, "It is a flavor salt. Blinded tests mostly do not reproduce the syndrome stories."],
    ["Honey never spoils, so a jar from a tomb is lunch", P, "Sealed honey can last a very long time. Archeology snacks are still a bad idea."],
    ["Local honey cures your pollen allergies", F, "A sweet folk remedy. Allergy shots are not the same as a spoon of honey."],
    ["Sea salt has no sodium so it is free to pour", F, "It is still salt. The mineral extras are tiny."],
    ["Himalayan pink salt heals the body with extra minerals", F, "Pretty crystals, still mostly sodium chloride. It is not a multivitamin."],
    ["Brown sugar is a health food compared with white", F, "It is white sugar with molasses put back. Calories do not care about the color."],
    ["Agave syrup is a natural free pass for sugar", F, "It is still sugar, often high in fructose. Natural is not a shield."],
    ["Celery has negative calories so you lose weight by chewing it", F, "It is low calorie. Chewing does not burn more than the celery holds."],
    ["Lemon water in the morning melts fat", F, "Hydration is fine. Fat does not dissolve in citrus."],
    ["Apple cider vinegar cures most illnesses", F, "It is a sour condiment. It is not a pharmacy."],
    ["Detox teas flush toxins out of your organs", F, "Your liver and kidneys already do that. Many teas just make you visit the bathroom."],
    ["Charcoal lemonade cleans your blood", F, "Medical charcoal is for some poisonings in a clinic. A party drink is theater."],
    ["Alkaline diets change your blood pH for the better", F, "Blood pH is buffered. Food does not flip it like a switch."],
    ["You can spot-reduce belly fat with sit-ups", F, "You strengthen the muscle under the fat. The fat leaves by overall diet and movement, not by local begging."],
    ["Sweat is fat leaving the body", F, "Sweat is water and salt. Fat leaves mostly as carbon dioxide you breathe out."],
    ["No pain, no gain means injury is a good workout", F, "Effort can sting. Sharp pain is a stop sign."],
    ["Running always destroys your knees", F, "Load can bother some knees. Recreational running is not a guaranteed wrecking ball."],
    ["Creatine is a steroid", F, "It is a legal supplement the body already makes. It is not anabolic steroid chemistry."],
    ["Protein powder wrecks healthy kidneys", F, "People with kidney disease need medical advice. Healthy kidneys handle ordinary protein."],
    ["Soy foods give men breasts", F, "Ordinary food amounts do not estrogenize men into a cartoon. The internet serving is the myth."],
    ["Coffee stunts your growth", F, "Caffeine is a stimulant. It is not a height tax."],
    ["Tea dehydrates you more than it hydrates", F, "Caffeinated drinks still count toward fluid. They are not dry."],
    ["Alcohol warms you up in the cold", F, "It flushes skin and can make you feel warm while you lose heat. A dangerous campfire story."],
    ["Coffee sobers you up so you can drive", F, "It can make a tired drunk person a more awake drunk person. Time clears alcohol."],
    ["Hair of the dog cures a hangover", F, "More alcohol delays the bill. It is not medicine."],
    ["Chocolate is toxic to people the way it is to dogs", F, "Theobromine hits dogs harder. Humans handle chocolate in food amounts."],
    ["A dog's mouth is cleaner than a human's", F, "Different microbes, not a hygiene trophy. Do not take medical advice from a lick."],
    ["A wagging tail always means a friendly dog", F, "Wags have moods. A stiff or high wag can be trouble."],
    ["Pit bulls have locking jaws", F, "Their jaws work like other dogs. Breed laws are politics, not a mechanical latch."],
    ["Cats always land on their feet from any height", P, "They right themselves well. Extreme falls still injure or kill."],
    ["Goldfish grow only to the size of the bowl as a kindness", F, "A tiny bowl stunts and stresses them. They can grow much larger in decent water."],
    ["Elephants are afraid of mice", U, "Startle exists. A species-wide mouse phobia is a cartoon."],
    ["Penguins fall over watching airplanes", F, "A cute story that did not hold up as a real epidemic of fainting birds."],
    ["Polar bear fur is white", F, "The hairs are hollow and look white. The skin underneath is dark."],
    ["Piranhas strip a cow to bones in seconds", P, "They can bite. The boiling-river skeleton scene is movie math."],
    ["Sharks do not get cancer", F, "Sharks get tumors. The cartilage-pill story oversold a hope."],
    ["Dolphins are always friendly to humans", F, "They are wild. Some are curious. Some have injured people."],
    ["Snakes are charmed by the music of the flute", F, "They follow the motion. They do not have external ears for the tune."],
    ["Snakes chase people for revenge", F, "Most want an exit. A few defend a patch. Grudge plots are human."],
    ["All bees die when they sting", P, "Honey bees often leave the stinger and die. Bumblebees and wasps can sting again."],
    ["Earwigs crawl into ears to lay eggs in the brain", F, "The name is a scare. They prefer damp gardens, not your skull."],
    ["Cockroaches would be the last species after a nuclear war", P, "They handle radiation better than people. They are not magic."],
    ["Toads give you warts", F, "Warts are viruses. Toad bumps are their skin, not a gift."],
    ["Daddy longlegs are the most venomous spiders but cannot bite you", F, "The species people mean are not record-venom spiders, and the punchline is a bar story."],
    ["Bats get stuck in people's hair on purpose", F, "They hunt insects and avoid faces. Hair is not a net they seek."],
    ["If you kill a spider it will rain", F, "Weather does not take spider attendance."],
    ["Ladybugs in the house mean money is coming", F, "They overwinter indoors. Your bank does not."],
    ["A wishbone wish always goes to the bigger half", F, "It is a poultry toy. Luck is not in the fork."],
    ["Marie Antoinette said let them eat cake", F, "The line is older than her crisis. It stuck because it painted her as cruel."],
    ["Medieval Europeans thought the Earth was flat", F, "Educated medieval people knew a sphere. The Columbus flat-Earth tale is later packaging."],
    ["Cleopatra was an Egyptian pharaoh of local ethnicity", P, "She ruled Egypt. Her dynasty was Macedonian Greek."],
    ["The forbidden fruit in Genesis is named as an apple", F, "The text says fruit. Apples are later art and translation habit."],
    ["Salem witches were burned at the stake", F, "In Salem they were hanged, and one was pressed. Burning is a different European picture."],
    ["Vikings invaded in horned helmets", F, "Opera costumes put the horns on. War helmets were practical."],
    ["Ninjas always dressed in all-black pajamas", F, "Night black is theater. Real spies looked like the crowd."],
    ["The library of Alexandria was destroyed in one villain night", P, "It declined across incidents and centuries. One cartoon fire is too neat."],
    ["Van Gogh cut off his whole ear in a single clean myth", P, "He injured his ear. The exact piece and motive are argued. It was not a tidy whole-ear souvenir."],
    ["The customer is always right as a law", F, "It is a slogan from retail. Law and safety still outrank a tantrum."],
    ["Finders keepers is how lost property works", F, "Lost-and-found and theft laws exist. A wallet is not a prize."],
    ["You automatically get married after seven years of living together", F, "A few places have narrow common-law rules. Seven years is not a worldwide spell."],
    ["Police must tell you they are police when asked or the arrest is fake", F, "Undercover work exists. TV rules are not the statute book."],
    ["If they skip Miranda rights you walk free no matter what", P, "Statements can get excluded. The whole case does not always vanish."],
    ["You can yell fire in a crowded theater as the complete free-speech rule", P, "The old line is a metaphor from a case. Real speech law is more specific."],
    ["Africa is a country", F, "It is a continent of many countries. The mix-up erases a lot of people."],
    ["The Amazon rainforest is the planet's lungs that make most of our oxygen", P, "It matters hugely for carbon, water, and life. Most breathable oxygen is from the ocean and other plants too."],
    ["A cold day disproves a warming climate", F, "Weather is a day. Climate is the long pattern."],
    ["Plastic in the ocean is mostly drinking straws", F, "Straws are a visible slice. Fishing gear and other waste are huge."],
    ["Recycling means every bottle you rinse becomes a new bottle", P, "Some loops work. A lot still is downcycled, exported, or dumped. The bin is not a magic circle."],
    ["Electric cars are always dirtier than petrol cars", F, "Making the battery has a cost. Over the life of the car, the mix of power usually wins for EVs in many grids."],
    ["Chemtrails are a secret spraying program from airliners", F, "You are seeing contrails, ice from exhaust in cold air. The conspiracy needs a cast of thousands."],
    ["5G towers spread viruses", F, "Radio waves are not a virus taxi. Phones did not invent measles."],
    ["Wi-Fi in the home causes cancer", U, "Wi-Fi is low-power radio. Major reviews have not shown a cancer mechanism at those levels."],
    ["Airplanes dump toilet waste on houses", F, "Blue-ice incidents are rare failures. Toilets are not an open hatch over suburbs."],
    ["Fluoride in water is a mind-control plot", F, "It is added in some places to reduce cavities. That is dental policy, not hypnosis."],
    ["The moon landings were filmed in a studio", F, "Independent tracking, rocks, and later photos of the sites back the landings. The studio story needs a planet-sized cover-up."],
    ["The Earth is a flat disc with a rim of ice", F, "Ships, time zones, photos, gravity, and eclipses all fit a globe. The disc does not."],
    ["Weighing a dying person proved the soul weighs 21 grams", F, "A tiny old experiment with bad controls. Bodies do not shed a standard soul weight."],
    ["Polygraph tests never lie", F, "They track nerves, not truth. Plenty of people beat them or fail while honest."],
    ["CSI-style zoom-and-enhance can always read a plate from a smudge", F, "You cannot invent pixels that were never captured. TV detective cameras are fiction."],
    ["Hypnosis can make you cluck like a chicken forever against your will", F, "Stage shows pick willing people. You do not get stuck as poultry."],
    ["Past-life regression recovers real memories", F, "People can imagine vivid scenes under suggestion. That is not a birth certificate from 1400."],
    ["Slender Man is an old European folklore figure", F, "He is a modern internet character. The suit and tentacles are new."],
  ]),
  ...pack("health", [
    ["Sugar makes children hyperactive", F, "Blinded tests keep finding the rush is the party, not a unique sugar intoxication."],
    ["Shaved hair grows back thicker and darker", F, "The blunt stub feels coarse. The follicle is not switching to a new species of hair."],
    ["You must wait 30 minutes after eating before you swim or you will drown", F, "A full stomach can feel sluggish. It is not a drowning spell."],
    ["Feed a cold, starve a fever", F, "Sick people need fluid and enough food. The proverb is not a protocol."],
    ["You catch a cold from being cold", P, "Viruses cause colds. Winter crowding and dry air help them. A chill alone is not the germ."],
    ["Wet hair in winter causes pneumonia", F, "Pneumonia is infection. Wet hair makes you cold, not automatically infected."],
    ["Sitting too close to the TV permanently ruins your eyes", F, "It can strain and annoy. It does not burn the screen into the retina like a curse."],
    ["Reading in dim light ruins your eyesight forever", F, "It is tiring. It is not a proven way to need glasses as punishment."],
    ["Glasses make your eyes weaker so you should delay them", F, "Lenses correct the blur. They do not addict the eyeball into collapse."],
    ["Contact lenses can slip behind your eyeball and get lost", F, "The conjunctiva is a cul-de-sac. They can tuck under an eyelid, not migrate into the skull."],
    ["20/20 vision means perfect eyes", P, "It is a sharpness score at a distance. Color, field, and focus at near still matter."],
    ["Blind people automatically have super hearing", P, "Some people get better at using sound. It is practice and brain space, not a free upgrade for everyone."],
    ["Sign language is the same in every country", F, "Many sign languages exist. They are not pantomime that everyone already knows."],
    ["Acne is caused by chocolate and greasy food as a rule", P, "Diet can play a role for some. Faces also have hormones and pores. Chocolate is not a spell."],
    ["Tanning is a healthy protective glow", F, "A tan is injury. A 'base tan' is weak armor compared with actual shade and sunscreen."],
    ["You do not need sunscreen on cloudy days", F, "UV gets through cloud. Burns happen on overcast beaches too."],
    ["Sunscreen causes cancer so skip it", F, "UV is the proven skin-cancer driver. Use the lotion; do not treat a scare headline as a beach plan."],
    ["Breakfast is medically the most important meal as a law of nature", P, "Some people do well with it. Skipping is not a moral failure if you eat well later."],
    ["Carbs after 6 p.m. turn straight into fat", F, "Calories and overall diet matter more than a clock curfew."],
    ["Organic food never uses pesticides", F, "Organic rules allow some sprays. Organic is a farming standard, not a zero-chemical halo."],
    ["Natural always means safe", F, "Poison ivy is natural. Dose and evidence still count."],
    ["Vaccines cause autism", F, "The scare paper was retracted. Large studies do not show that link. The diseases are real."],
    ["You can sweat out a hangover in a sauna instead of drinking water", F, "You lose more fluid. Rest and water are the boring fix."],
    ["Spicy food causes stomach ulcers", F, "Most ulcers are bacteria or medicines. Chili can annoy; it is not the main villain."],
    ["Chicken soup cures a cold", P, "Steam, salt, and care can ease symptoms. It is not an antiviral pill."],
    ["Cracking your neck is the same as medical chiropractic", F, "A party crack is not a diagnosis. Neck popping can be risky if you force it."],
    ["You need a detox juice to rest your liver", F, "The liver does not clock out for kale. Food and not drinking too much are the actual rest."],
    ["Cold showers massively boost testosterone", U, "They wake you up. They are not a proven hormone factory."],
    ["Vaping is just harmless water vapor", F, "It is an aerosol with chemicals. It is usually less bad than smoking, not a cloud of spa mist."],
    ["Light cigarettes are a safer cigarette", F, "People compensate with bigger puffs. 'Light' was a marketing word."],
    ["Marijuana has no risks because it is a plant", F, "Plants can still affect lungs, driving, and some minds. Legal is not the same as none."],
    ["CBD gets you high like THC", F, "CBD is not the same intoxicant. Labels are messy; products vary."],
    ["You should wash your hair every day or it is dirty", F, "Scalps differ. Daily shampoo is a habit, not a health inspector rule."],
    ["Dandruff is only dry scalp", P, "It can be yeast, oil, or dryness. One shampoo story does not cover all flakes."],
    ["You can catch a virus from a toilet seat instantly as the main path", P, "Hands, air, and close contact matter more than a brief sit."],
  ]),
  ...pack("science", [
    ["The Great Wall of China is visible from space with the naked eye", F, "From low orbit, many human things can be seen in the right light. The Wall is not a unique easy stripe from the Moon or casual glances."],
    ["Dogs age exactly seven years for every human year", F, "Aging is faster early, then slows, and size matters. Seven is a rough cartoon."],
    ["Humans evolved from chimpanzees living today", F, "We share an ancestor. Chimps are cousins, not grandparents."],
    ["The full moon makes people go mad and fill hospitals", F, "Big studies keep failing the lunar crime-and-birth spike. We notice the nights we already believe in."],
    ["More babies are born on a full moon", F, "Birth rooms feel busy. The moon phase does not run the ward."],
    ["You can see a flag on the Moon with a backyard telescope", F, "The flags are tiny. Even serious amateur scopes cannot read them."],
    ["Stars are tiny fires that sit just above the clouds", F, "They are suns at enormous distance. Air makes them twinkle."],
    ["The Sun is a small hot disk a few thousand miles away", F, "It is a star about 150 million kilometers away. Eclipses and transits fit that scale."],
    ["Lightning never hits ships because of the rubber tires on cars, so boats are safe", F, "Cars can shield you because of the metal shell, not the tires. Boats and open water are a different, worse story."],
    ["Rubber shoes make you lightning-proof in a field", F, "Soles are not a Faraday cage. Get low, skip the lone tree, and get inside if you can."],
    ["The sky is blue because it reflects the sea", F, "Air scatters blue light. Dry deserts still have blue noon skies."],
    ["Water going down a drain proves which hemisphere you are in", F, "Sinks are messy. Coriolis is real at weather scale, not in a bathroom bowl."],
    ["A duck's quack does not echo", F, "Quacks can echo. The saying is a cute falsehood."],
    ["Chameleons change color only for camouflage", P, "Mood, temperature, and signaling matter a lot. Background matching is not the whole software."],
    ["Bulls hate the color red", F, "The cape's motion matters. Cattle do not see red as a rage switch."],
    ["Ostriches bury their heads in sand to hide", F, "They check the ground and nests. The buried-head poster is a cartoon."],
    ["Camels store water in their humps", F, "Humps are fat. Water is saved by kidneys and other tricks."],
    ["Goldfish remember things for three seconds", F, "They can learn tanks and cues for months. The joke became a factoid."],
    ["Bats are blind", F, "They see. Echolocation is extra, not a white cane."],
    ["Touching a baby bird makes the parents abandon it", F, "Most birds barely smell you. Putting a fallen nestling back is often right."],
    ["Lemmings jump off cliffs on purpose", F, "A film staged the suicide march. Real lemmings boom and bust without a death cult."],
    ["Humans use only 10 percent of their brain", F, "Scans and injuries show we use the whole organ. The 10 percent line is a pep talk."],
    ["Different tongue zones taste only one flavor each", F, "Taste types are spread around. The school map was wrong."],
    ["Deoxygenated blood is blue until it hits air", F, "Blood is red. Veins look blue because of light in skin."],
    ["Hair keeps growing after you die", F, "Skin shrinks and makes stubble look longer. The follicles are not still at work."],
    ["A penny dropped from a tower can kill a person", F, "Air drag keeps it from becoming a bullet. It can sting."],
    ["Glass in old windows is a slow liquid that has sagged", F, "Old glass was made uneven and often installed thick-edge down. It is an amorphous solid."],
    ["Mount Everest is the farthest point from Earth's center", F, "Chimborazo wins that because the planet bulges at the equator."],
    ["The dark side of the Moon never gets sunlight", F, "The far side faces away from us. It still has day and night."],
    ["Black holes suck everything from light-years away like vacuums", F, "At a distance they gravity like any equal mass. You have to get close."],
    ["There is no gravity in space, that is why astronauts float", F, "They are in free fall around Earth. Gravity is still doing the orbit."],
    ["The North Star is the brightest star in the night sky", F, "Sirius is brighter. Polaris is useful, not the lamp."],
    ["Raindrops are shaped like teardrops", F, "Small ones are round. Bigger ones flatten on the bottom."],
    ["All deserts are hot sand", F, "Deserts are dry. Antarctica counts. Many are rock."],
    ["Saturn is the only ringed planet", F, "The other giants have rings too. Saturn's are the show."],
    ["Pluto was demoted because it is not round", F, "It is round. The neighborhood-clearing rule is what moved it."],
    ["The asteroid belt is a crowded junkyard ships must dodge", F, "It is mostly empty. Probes cross without weaving."],
    ["A comet tail always streams behind it like exhaust", F, "Tails point away from the Sun, even when the comet is heading out."],
    ["You can hear explosions in space like in movies", F, "No air, no ordinary sound. The boom is for the soundtrack."],
    ["The Big Bang was an explosion in empty space at a point you could stand next to", F, "It is the expansion of space itself. There is no outside bleacher."],
    ["Evolution means an animal tries hard and becomes a new species in its lifetime", F, "Populations change over generations. One giraffe cannot wish a longer neck for the species."],
    ["If people evolved from apes, apes should have disappeared", F, "Cousins can both live. We did not replace every ape."],
    ["The second law of thermodynamics forbids life", F, "Earth is open to the Sun. Order locally is allowed when energy flows."],
    ["Mutations are always harmful", F, "Many are silent. Some help. Selection sorts."],
    ["Identical twins have identical fingerprints", F, "Same genes, different ridge details from the womb."],
    ["Eye color is one gene with two switches", F, "Several genes mix it. Two brown-eyed parents can have a blue-eyed child."],
    ["Red hair is going extinct", F, "Recessive traits hide in carriers. There is no countdown clock."],
    ["You can change blood type by eating certain foods", F, "Blood type is genetic. Lunch does not rewrite it."],
    ["The appendix has no function at all", P, "It can inflame. It may also house useful microbes. 'Useless leftover only' is too neat."],
    ["The funny bone is a bone", F, "It is the ulnar nerve at the elbow."],
    ["Sneezes stop your heart", F, "They change pressure. They do not switch the heart off."],
    ["Knuckle cracking releases toxins", F, "It is a pressure pop in the joint. Not a cleanse."],
    ["Boiling water always makes any toxin safe", F, "It can kill many microbes. Some toxins and spores remain."],
    ["Freezing food kills all bacteria", F, "Cold pauses growth. Many microbes survive the freezer."],
    ["Microwaves make food radioactive", F, "They shake water molecules. They do not irradiate leftovers."],
    ["The Sun is yellow as seen from space", P, "Its light is close to white. Air can paint it yellow or red."],
    ["Seasons happen because Earth is closer to the Sun in summer", F, "Tilt causes seasons. Northern summer is not the closest point."],
    ["Lightning never strikes the same place twice", F, "Tall conductors get hit again and again."],
    ["The Great Wall is the only human thing visible from the Moon", F, "From the Moon, even continents are a stretch by eye. The Wall is far too thin."],
  ]),
  ...pack("history", [
    ["Napoleon was tiny even for his time", F, "He was around average. British cartoons and inch conversions built the legend."],
    ["Einstein failed mathematics as a child", F, "He was strong at math. A later mix-up of exams made a better story."],
    ["Vikings wore horned helmets in battle", F, "Costume horns came later. Real helmets were iron caps."],
    ["Cowboys in the 1800s all wore the same movie hat and said partner every sentence", F, "Hats and slang varied. Hollywood standardized the look."],
    ["The Titanic's builders claimed it was unsinkable as a legal guarantee", P, "Press and hype used the word. Engineering still had bulkheads that did not go high enough."],
    ["Thanksgiving turkey makes you sleepy only because of tryptophan", P, "Tryptophan exists. The nap is also a big meal, alcohol, and a couch."],
    ["Paul Revere finished the ride alone shouting the British are coming", P, "He was one rider, was detained, and the warning was more complicated than a solo shout."],
    ["The first Thanksgiving looked like a modern grocery-store feast", F, "The 1621 meal is thinly documented. Turkey-and-pie posters are later American branding."],
    ["George Washington had wooden teeth", F, "His dentures used other materials, including ivory and human teeth. Wood is the cartoon."],
    ["The Great Fire of London was started by a baker as a proven plot", P, "It started in Pudding Lane near a bakery. A plot is extra."],
    ["Nero fiddled while Rome burned", F, "Fiddles were later. The story is hostile gossip about a ruler."],
    ["Gladiators always fought to the death", F, "They were expensive. Many bouts ended without a kill."],
    ["Pyramid stones were pulled by slaves under whips as the only method", P, "Workers included laborers with housing and pay evidence. The whip-only cartoon is too simple."],
    ["The Trojan Horse is confirmed archaeology", U, "The war stories are old. A giant wooden horse as described is literature until wood shows up."],
    ["King Arthur pulled a sword from a stone in a dated year we can stamp", U, "Arthur is legend layered on maybe-warlords. The stone is story."],
    ["Columbus discovered America as empty land", F, "People had lived there for millennia. He reached islands in the Caribbean, not a vacant continent."],
    ["The American Civil War was only about states' rights in the abstract", P, "States' rights to what? Contemporary documents put slavery at the center."],
    ["The 1969 moon landing used studio lighting because shadows look studio-like", F, "Multiple light sources on the Moon include reflected ground light. The studio claim fails other tests."],
    ["Shakespeare did not write the plays because a commoner could not", U, "Authorship theories exist. The documentary trail still points to the actor from Stratford for most scholars."],
    ["The Dark Ages were centuries with zero learning", F, "The name is a later insult. Monasteries, empires, and science still happened."],
    ["People in the past only lived to 30 so nobody was old", F, "Child mortality pulled the average down. Adults often reached 50s and 60s."],
    ["Spices in the Middle Ages were used to hide rotten meat", F, "Spices were expensive. Rotten meat is still rotten. People preferred fresh when they could."],
    ["Chastity belts were a common medieval device", F, "Most surviving stories and objects are later jokes or museum fakes."],
    ["The Spanish Inquisition killed tens of millions", F, "It was brutal and real. The cartoon body count is inflated."],
    ["Witches in Europe were mostly burned after a Pope declared physics illegal", P, "Witch hunts happened, with regional methods. The one-decree cartoon skips politics and panic."],
    ["An apple hit Newton on the head and gravity was invented that afternoon", P, "He did think about falling fruit. The bonk-on-the-head scene is storytelling."],
    ["Edison alone invented the light bulb from nothing", F, "Many people worked on incandescent lamps. Edison sold a system that lasted."],
    ["Ford invented the car", F, "He made cars ordinary with the assembly line. Automobiles already existed."],
    ["The internet was invented by one company in the 1990s", F, "Packet networks go back decades. The web is one layer on top."],
  ]),
  ...pack("technology", [
    ["Microwaves leak radioactivity into leftovers", F, "They use non-ionizing waves. The food is not a source after the beep."],
    ["You should not use a phone in a gas station because it will spark a pump", F, "The scare posters outran the evidence. Static and smoking are the more serious pump risks."],
    ["Computers used to weigh tons so a smartphone cannot be more powerful than Apollo", P, "Apollo computers were impressive for the job. A phone has far more raw compute; the missions still had brilliant engineering."],
    ["The cloud is a literal building full of fog", F, "It is other people's computers in data centers. Fog is branding."],
    ["Private browsing means nobody can see what you did", F, "It skips local history. Your school, boss, ISP, and the site can still see plenty."],
    ["Incognito mode makes you anonymous to the website", F, "You look like a logged-out visitor. You are not a ghost."],
    ["A paperclip on a USB stick always means it is safe", F, "Hardware can lie. Trust the source, not the office stationery."],
    ["You can charge a phone from a fruit battery enough to call home", P, "A demo can tick a clock. It will not run your week."],
    ["More megapixels always means a better camera", F, "Sensor size, lenses, and light matter more. Extra pixels can just be noise."],
    ["Closing apps on your phone always saves a lot of battery", P, "Force-closing can make them work harder next open. Screens and radios spend more."],
    ["Leaving a phone to charge overnight always ruins the battery by morning", P, "Modern phones taper the charge. Heat and many cycles age batteries more than one night."],
    ["You need to drain a lithium battery to zero often to calibrate it", F, "Old nickel advice. Lithium prefers mid-range, not funeral cycles."],
    ["Aluminum foil on your router makes the Wi-Fi illegal-grade strong", P, "A reflector can shape a signal. It can also make neighbors' Wi-Fi worse. It is not a superpower."],
    ["A Faraday bag is only for spies in movies", F, "Blocking radio is real physics. Ordinary people use them for travel cards and privacy too."],
    ["QR codes can steal your bank PIN just by being looked at", P, "A code can open a bad site. Looking is not magic; tapping and typing still matter."],
    ["All .gif pronunciations are settled by one inventor forever", U, "The inventor said jif. English still argues. It is not a safety issue."],
    ["You should shake a laser printer like a ketchup bottle when it jams", F, "You can spill toner and break doors. Follow the jam diagram."],
    ["Putting a phone in rice always saves it from water", P, "Rice is a folk fix. Power off, dry, and professional help beat a bag of grains. Corrosion still happens."],
    ["A factory reset means the old files are gone from Earth", P, "It helps. Determined recovery can still find remnants on some storage. Sensitive phones need stronger wipe tools."],
    ["The first Google result is always the true one", F, "Rank is not a court. Check who wrote it."],
    ["Wikipedia can never be trusted because anyone can edit", P, "Anyone can try. Popular pages are watched. Still, follow the citations."],
    ["AI chatbots cannot be wrong if they sound confident", F, "Fluent is not sourced. They invent citations. Check anyway."],
    ["Autocorrect proves your phone is listening through the camera", F, "It predicts from what you type and what people type. Creepy ads have other pipelines too."],
    ["Blue light from phones is the only reason you cannot sleep", P, "Light at night can matter. Caffeine, worry, and the content of the feed matter too."],
    ["Dark mode saves a huge amount of battery on every phone", P, "OLED panels can save power with black pixels. LCD savings are small."],
    ["You can overclock a microwave to mine cryptocurrency", F, "Please do not. Microwaves heat food. They are not GPUs."],
    ["3D printers at home already print working human kidneys", F, "Hobby machines print plastic. Organs are research."],
    ["Self-driving cars have solved driving in every rainstorm", F, "Some systems help on mapped roads. Weather, chaos, and edge cases remain."],
    ["A VPN makes you untraceable to everyone", P, "It hides you from the local cafe Wi-Fi. The VPN company can still see a lot unless you trust it."],
    ["Incandescent bulbs are illegal everywhere so you cannot buy light", F, "Efficiency rules shifted the market. LEDs exist. The black-market-light story is extra."],
  ]),
];
